import { useState, useRef, useEffect, useId } from 'react'
import { getSuggestions } from '../api/suggestions'
import { rankSuggestions } from '../utils/taxonomy'
import { comboboxKeydown, optionsChanged, initialCombobox, type ComboboxState } from '../utils/comboboxReducer'

// Default-Pool (Rechnungs-/Auftrags-TITEL — projektbezogen formuliert).
// Dedup via Set: neue Blöcke können gefahrlos ergänzt werden.
export const TITLE_SUGGESTIONS = [...new Set([
  // Website (wertorientiert)
  'Website-Erstellung & Einrichtung',
  'Website-Redesign & Optimierung',
  'Website-Relaunch & Modernisierung',
  'Website-Erstellung (WordPress)',
  'Website-Erstellung (React)',
  'Website-Pflege & Aktualisierung',
  'Performance- & Ladezeit-Optimierung',
  'Website-Migration & Relaunch',
  'Landing Page mit Conversion-Optimierung',
  'Responsive Anpassung & Mobile-Optimierung',
  'Barrierefreiheit & Accessibility-Optimierung',
  // SEO
  'SEO-Optimierung',
  'SEO-Grundoptimierung',
  'SEO-Analyse und Beratung',
  'SEO-Audit',
  'Google Search Console Einrichtung',
  // Hosting & Domain
  'Hosting-Einrichtung',
  'Hosting-Migration',
  'Domain-Einrichtung',
  'SSL-Zertifikat Einrichtung',
  'Server-Konfiguration',
  'E-Mail-Einrichtung',
  // Entwicklung
  'Webentwicklung',
  'Frontend-Entwicklung',
  'Backend-Entwicklung',
  'Fullstack-Entwicklung',
  'App-Entwicklung',
  'API-Entwicklung',
  'Datenbankentwicklung',
  'Plugin-Entwicklung',
  'Schnittstellenentwicklung',
  'Softwareentwicklung',
  // Beratung
  'IT-Beratung',
  'Technische Beratung',
  'Digitalisierungsberatung',
  'Prozessoptimierung',
  'Systemarchitektur-Beratung',
  // Wartung & Support
  'Technischer Support',
  'Wartungsvertrag',
  'Fehlerbehebung',
  'Bugfix',
  'Sicherheitsupdate',
  'Performance-Optimierung',
  'Ladezeit-Optimierung',
  'Backup-Einrichtung',
  // Content & Design
  'Content-Einpflege',
  'Content-Erstellung',
  'Bildbearbeitung',
  'Logo-Erstellung',
  'Corporate Design',
  'UI/UX Design',
  'Grafikdesign',
  // Security
  'Sicherheitscheck',
  'Sicherheitsaudit',
  'Penetrationstest',
  'DSGVO-Beratung',
  'Datenschutzanpassung',
  'Cookie-Banner Einrichtung',
  // Sonstige
  'Schulung',
  'Workshop',
  'Projektmanagement',
  'Code-Review',
  'Datenübernahme',
  'KI-Integration',
  'KI-gestützte Entwicklung',
  'Automatisierung',
  'Monitoring-Einrichtung',
  'Analytics-Einrichtung',
  'Google Analytics Setup',
  'Social Media Integration',
  // Änderungen an bestehender Website
  'Änderungen an Website',
  'Änderungen an bestehender Website',
  'Website-Anpassungen',
  'Website-Aktualisierung',
  'Website-Umbau',
  'Inhaltliche Anpassungen Website',
  'Layout-Anpassungen Website',
  'Design-Anpassungen Website',
  'Navigations-Umbau',
  'Footer-Anpassung',
  'Header-Anpassung',
  'Menü-Umbau',
  'Neue Unterseite erstellen',
  'Seite entfernen / archivieren',
  'Formular-Anpassung',
  'Formular-Erweiterung',
  'Integration neuer Funktion',
  'Entfernen veralteter Funktion',
  'Überarbeitung Startseite',
  'Überarbeitung Kontaktseite',
  'Überarbeitung Impressum/Datenschutz',
  'Textänderungen Website',
  'Bilder-Austausch Website',
  'Link-Anpassungen',
  'Redirect-Einrichtung (301)',
  'Broken-Link-Korrektur',
  // Sicherheits-Anpassungen
  'Sicherheits-Anpassungen',
  'Sicherheits-Update',
  'Sicherheits-Review',
  'Sicherheitshärtung',
  'Sicherheits-Patches',
  'Server-Härtung',
  'Firewall-Konfiguration',
  'WAF-Einrichtung (Web Application Firewall)',
  'Brute-Force-Schutz einrichten',
  'Rate-Limiting einrichten',
  'HTTP-Security-Header setzen',
  'Content-Security-Policy (CSP) konfigurieren',
  'Zwei-Faktor-Authentifizierung einrichten',
  'Login-Schutz (2FA, Captcha)',
  'Admin-Zugang absichern',
  'Benutzerrechte-Überprüfung',
  'Passwortrichtlinien einrichten',
  'Session-Management absichern',
  'DDoS-Schutz konfigurieren',
  'IP-Whitelisting / Blacklisting',
  'Malware-Scan',
  'Malware-Entfernung',
  'Virus-Bereinigung',
  'Hack-Bereinigung und Recovery',
  'Schwachstellen-Scan',
  'Security-Audit',
  'Intrusion Detection Setup',
  'Log-Monitoring einrichten',
  'Backup-Strategie überarbeiten',
  'Disaster-Recovery-Plan',
  'SSL/TLS-Konfiguration prüfen',
  'Verschlüsselung implementieren',
  'Datenverschlüsselung at-rest',
  'Zertifikat-Erneuerung',
  'SSL-Migration auf HTTPS',
  'Veraltete Software-Updates',
  'CMS-Core-Update',
  'Plugin-Sicherheitsupdates',
  'Abhängigkeits-Updates (npm/composer)',
  'CVE-Patching',
  // Datenbank & Backend
  'Datenbank-Optimierung',
  'Datenbank-Backup',
  'Datenbank-Migration',
  'Datenbank-Reparatur',
  'Caching-Einrichtung (Redis/Memcache)',
  'Queue-System einrichten',
  'Cronjobs einrichten',
  // DevOps & Infrastruktur
  'Server-Umzug',
  'Deployment-Automatisierung',
  'CI/CD-Pipeline Setup',
  'Docker-Containerisierung',
  'Kubernetes-Setup',
  'Load-Balancer-Konfiguration',
  'Staging-Umgebung einrichten',
  'Test-Umgebung einrichten',
  // E-Commerce / Shop
  'Shop-Einrichtung',
  'Shop-Anpassungen',
  'Produkt-Import',
  'Zahlungsanbieter-Integration',
  'Versand-Module konfigurieren',
  'Newsletter-Integration',
  // Mobile / PWA
  'PWA-Einrichtung',
  'App-Store-Einreichung',
  'Mobile-Testing',
  // Monitoring & Analyse
  'Uptime-Monitoring Setup',
  'Error-Tracking Setup (Sentry)',
  'Performance-Monitoring',
  'Analytics-Dashboard',
  // Cloud & Infrastruktur
  'Cloud-Migration',
  'AWS-Einrichtung',
  'Azure-Einrichtung',
  'Hetzner/DigitalOcean Setup',
  'Mailserver-Konfiguration',
  'DNS-Umstellung',
  'CDN-Einrichtung (Cloudflare)',
  // IT-Betreuung / Vor-Ort
  'IT-Betreuung (Vor-Ort)',
  'IT-Betreuung (Remote)',
  'Arbeitsplatz-Einrichtung',
  'Arbeitsplatz-Konfiguration',
  'Rechner-Einrichtung',
  'Notebook-Einrichtung',
  'E-Mail-Konfiguration',
  'Browser-Einrichtung',
  'Software-Installation',
  'Drucker-Einrichtung',
  'Netzwerk-Einrichtung',
  'WLAN-Optimierung',
  'VPN-Einrichtung',
  'Datenmigration',
  'Datenrettung',
  'Hardware-Austausch',
  // Recherche & Reporting
  'Recherche und Report',
  'Rechtsrecherche und Dokumentation',
  'Technische Recherche',
  'Markt-/Wettbewerbsanalyse',
  'Gutachten / Stellungnahme',
  'Dokumentation erstellen',
  'Statusbericht',
  'Monitoring-Report',
  // Allgemein
  'Beratung und Umsetzung',
  'Projektbetreuung',
  'Anpassungen nach Absprache',
  'Diverse Leistungen (siehe Positionen)',
  // ── KI-Automatisierung (celox-Kernportfolio) ──
  'KI-Automatisierung Rechnungseingang',
  'KI-Automatisierung E-Mail-Bearbeitung',
  'KI-Automatisierung Dokumentenverarbeitung',
  'KI-Assistent für den Kundenservice',
  'KI-Chatbot-Einführung',
  'Interne KI-Wissensdatenbank (RAG)',
  'Automatisierungs-Potenzialanalyse',
  'Prozess-Audit und Automatisierungs-Roadmap',
  'Workflow-Automatisierung Vertrieb',
  'Workflow-Automatisierung Buchhaltung',
  'Workflow-Automatisierung Personalwesen',
  'Angebotsprozess-Automatisierung',
  'Berichtswesen-Automatisierung',
  'Reporting-Automatisierung',
  'KPI-Dashboard-Einführung',
  'Dashboard-Entwicklung',
  'Datenpipeline-Aufbau',
  'CRM-Einführung und Integration',
  'CRM-Automatisierung und Lead-Scoring',
  'Meeting-Transkriptions-Workflow',
  'Transkriptions-Service-Einrichtung',
  'Übersetzungs-Workflow-Einführung',
  'KI-Schulung für Mitarbeiter',
  'Prompt-Engineering-Workshop',
  'KI-Richtlinie und Governance',
  'KI-Reifegrad-Analyse',
  'Automatisierungs-Betreuung (monatlich)',
  'Sprachassistent-Integration',
  // ── Prozessoptimierung & Digitalisierung ──
  'Prozessoptimierung Auftragsabwicklung',
  'Prozessdigitalisierung Rechnungswesen',
  'Digitalisierung Posteingang',
  'Einführung papierloses Büro',
  'Dokumentenmanagement-Einführung (DMS)',
  'E-Rechnung-Umstellung (ZUGFeRD/XRechnung)',
  'GoBD-konforme Belegablage',
  'DATEV-Anbindung',
  'Buchhaltungs-Schnittstelle',
  'Digitale Personalakte-Einführung',
  'Vertragsverwaltung digitalisieren',
  'Formular-Digitalisierung',
  // ── Softwareentwicklung ──
  'Individualsoftware-Entwicklung',
  'Webanwendung-Entwicklung',
  'Kundenportal-Entwicklung',
  'Mitarbeiterportal-Entwicklung',
  'Buchungssystem-Entwicklung',
  'Terminbuchungssystem-Einführung',
  'Ticketsystem-Einführung',
  'Warenwirtschafts-Anbindung',
  'ERP-Schnittstellen-Entwicklung',
  'API-Anbindung Drittsystem',
  'Zahlungsintegration',
  'Kassensystem-Anbindung',
  'Warenbestand-Synchronisation',
  'Produktkonfigurator-Entwicklung',
  'Android-App-Entwicklung',
  'App-Modernisierung',
  'MVP-Entwicklung',
  'Prototyp-Entwicklung',
  'Software-Modernisierung (Legacy-Ablösung)',
  'Datenmigration Altsystem',
  'Softwarewartung (Jahresvertrag)',
  'Feature-Paket nach Anforderung',
  // ── Website & Shop ──
  'Website-Neuerstellung',
  'Unternehmenswebsite-Relaunch',
  'Onepager-Erstellung',
  'Landingpage-Paket',
  'Karriereseite-Erstellung',
  'Blog-Einrichtung',
  'Mehrsprachige Website',
  'Website-Barrierefreiheit (BFSG)',
  'Barrierefreiheits-Audit (BFSG)',
  'PageSpeed-Optimierung',
  'Website-Umzug und Konsolidierung',
  'Webshop-Erstellung',
  'Webshop-Relaunch',
  'Produktdaten-Migration Shop',
  'Website-Wiederherstellung',
  'Hack-Bereinigung Website',
  'Intranet-Aufbau',
  'Wiki-/Knowledge-Base-Einführung',
  // ── IT-Betrieb & Infrastruktur ──
  'IT-Betreuung (monatliche Pauschale)',
  'Managed IT-Services',
  'Wartungsvertrag Server',
  'Wartungsvertrag Website',
  'IT-Notfalleinsatz',
  'Vor-Ort-Support-Einsatz',
  'IT-Onboarding neuer Mitarbeiter',
  'IT-Offboarding',
  'Arbeitsplatz-Rollout',
  'Hardware-Beschaffung',
  'Homeoffice-Ausstattung',
  'Serverumzug',
  'Servermigration in die Cloud',
  'Cloud-Migration Microsoft 365',
  'Microsoft-365-Einführung',
  'Teams-Einführung',
  'SharePoint-Einführung',
  'Fileserver-Migration',
  'NAS-Einführung',
  'Netzwerk-Modernisierung',
  'WLAN-Ausbau',
  'Firewall-Erneuerung',
  'VPN-Einführung',
  'VoIP-Telefonanlage-Einführung',
  'Standortvernetzung',
  'Monitoring-Einführung',
  'Backup-Konzept und Einführung',
  'Disaster-Recovery-Konzept',
  'Virtualisierungs-Projekt',
  'Hochverfügbarkeits-Setup',
  'Skalierungs-Konzept',
  'Cloud-Kostenoptimierung',
  'IT-Umzug Büro',
  'Büro-Neueröffnung: IT-Ausstattung',
  'E-Mail-Migration',
  'E-Mail-Archivierung-Einführung',
  'Postfach-Konsolidierung',
  'Datenrettung',
  // ── IT-Sicherheit ──
  'IT-Sicherheits-Audit',
  'IT-Sicherheits-Check (Basis)',
  'Penetrationstest Webanwendung',
  'Penetrationstest Infrastruktur',
  'Schwachstellenanalyse',
  'Security-Awareness-Programm',
  'Phishing-Simulationskampagne',
  'Security-Schulung Belegschaft',
  'Zertifikats-Schulung Security (online)',
  'Notfallplan und Incident Response',
  'Ransomware-Vorsorge',
  'Incident-Response-Einsatz',
  'Forensik nach Sicherheitsvorfall',
  'Härtung Server-Infrastruktur',
  'E-Mail-Sicherheits-Paket (SPF/DKIM/DMARC)',
  'MFA-Einführung',
  'Passwort-Manager-Einführung',
  'Endpoint-Protection-Rollout',
  'Mobile-Device-Management-Einführung',
  'ISO-27001-Vorbereitung',
  'ISMS-Aufbau',
  'NIS2-Umsetzung',
  'IT-Grundschutz-Beratung',
  'Cyber-Versicherungs-Begleitung',
  // ── Datenschutz ──
  'DSGVO-Basis-Paket',
  'DSGVO-Audit',
  'Datenschutz-Dokumentation (VVT/TOM)',
  'AVV-Erstellung',
  'Datenschutzerklärung-Erstellung',
  'Cookie-Compliance-Umsetzung',
  'Externer Datenschutzbeauftragter (Pauschale)',
  'Datenschutz-Schulung',
  'DSGVO-Check Website',
  'Betroffenenanfragen-Bearbeitung',
  'Datenpannen-Unterstützung',
  // ── DSMS (datenschutz.celox.io) ──
  'DSMS-Einführung (datenschutz.celox.io)',
  'Datenschutz-Managementsystem – Einrichtung & Onboarding',
  'DSMS – Monatliche Nutzung & Betreuung',
  // ── Marketing & Sichtbarkeit ──
  'SEO-Paket (3 Monate)',
  'SEO-Betreuung (monatlich)',
  'Google-Ads-Einrichtung',
  'Google-Ads-Betreuung (monatlich)',
  'Google-Unternehmensprofil-Optimierung',
  'Newsletter-Einführung',
  'Social-Media-Starterpaket',
  'Content-Paket Website',
  // ── Beratung & Projekt ──
  'IT-Strategieberatung',
  'IT-Bestandsaufnahme',
  'Technologie-Audit',
  'Performance-Audit',
  'Code-Audit',
  'Architektur-Review',
  'Zweitmeinung IT-Angebot',
  'Anforderungsworkshop',
  'Konzeptphase Projekt',
  'Machbarkeitsstudie',
  'Technische Due Diligence',
  'Projektbegleitung (extern)',
  'Interim-IT-Leitung',
  'Retainer Beratung (monatlich)',
  'Fördermittelberatung Digitalisierung',
  // ── Pauschalen & Kontingente ──
  'Monatspauschale IT-Support',
  'Jahreswartung',
  'Hosting-Jahresgebühr',
  'Domain- und Hosting-Verwaltung (jährlich)',
  'Lizenzverlängerung',
  'SSL-Zertifikat-Verlängerung',
  'Supportkontingent (10 Stunden)',
  'Supportkontingent (20 Stunden)',
  'Stundenkontingent Entwicklung',
  // ── IoT & Sonstiges ──
  'Smart-Home-/Smart-Office-Installation',
  'IoT-Pilotprojekt',
  'IoT-Sensorik und Monitoring',
  'Digital-Signage-Einführung',
  'Schulungsplattform-Einführung',
  'E-Learning-Modul-Erstellung',
  'Onboarding-Portal-Einführung',
  'Messe-/Event-IT-Support',
  'Testphase und Qualitätssicherung',
  'Go-Live und Hypercare',
  'Projektabschluss und Übergabe',
  'Individuelle Leistung nach Vereinbarung',
  // ── CMS & Shop (konkret) ──
  'WordPress-Website-Relaunch',
  'WooCommerce-Shop-Einführung',
  'Shopware-Migration',
  'Shopify-Einrichtung',
  'TYPO3-Upgrade-Projekt',
  'Website-Baukasten-Ablösung',
  'Marktplatz-Anbindung (Amazon/eBay)',
  'Trusted-Shops-Integration',
  'Shop-Rechtstexte-Anbindung',
  // ── Entwicklung & Modernisierung ──
  'Framework-Upgrade',
  'PHP-Modernisierung',
  'Code-Refactoring-Paket',
  'Testautomatisierung-Einführung',
  'SSO-Einführung',
  'Passkey-Einführung',
  'Volltextsuche-Integration',
  'E-Signatur-Einführung',
  'Kundenspezifische Integration',
  'Datenmigrations-Projekt',
  // ── KI & Daten ──
  'KI-Telefonassistent',
  'Voice-Bot-Einführung',
  'Lokale-KI-Installation (Ollama)',
  'Vektor-Suche-Einführung',
  'KI-Wissensbasis-Pflege (monatlich)',
  'Chatbot-Training und Optimierung',
  'Datenanalyse-Projekt',
  'Power-BI-Dashboard',
  'Looker-Studio-Reporting',
  'Excel-Automatisierung',
  'CRM-Datenqualitäts-Projekt',
  'Datenbereinigung CRM',
  // ── Infrastruktur & Vor-Ort ──
  'Netzwerkverkabelung Büro',
  'Serverschrank-Aufbau',
  'Videoüberwachung-Einführung',
  'Zutrittskontrolle-Anbindung',
  'Gäste-WLAN-Einrichtung',
  'WLAN-Ausleuchtung',
  'Netzwerk-Audit',
  'Glasfaser-Umstellung',
  'Standort-Eröffnung IT',
  'Filial-Rollout',
  'Hardware-Refresh (Client-Erneuerung)',
  'Server-Hardware-Erneuerung',
  'Mac-Administration (Pauschale)',
  'Apple-MDM-Einführung',
  'Linux-Server-Setup',
  'Google-Workspace-Einführung',
  'Gmail-Migration',
  'Cloud-Exit / Rückmigration',
  'Lizenz-Optimierung',
  'Vendor-Wechsel-Begleitung',
  // ── Tools & Zusammenarbeit ──
  'Slack-Einführung',
  'Projektmanagement-Tool-Einführung',
  'Zeiterfassungs-Einführung',
  'Terminbuchungs-Einführung (Calendly)',
  'Digitale-Unterschriften-Einführung',
  // ── Managed Services ──
  'Managed Server (monatlich)',
  'Managed Client (monatlich)',
  'Managed Firewall (monatlich)',
  'Managed Backup (monatlich)',
  'SLA-Vereinbarung Betreuung',
  'Patchday-Betreuung (monatlich)',
  'Backup-Probe und Notfallübung',
  'IT-Jahresaudit',
  'Security-Quartals-Check',
  'Darkweb-Monitoring (monatlich)',
  'IT-Dokumentations-Projekt',
  // ── Security & Compliance (Ergänzungen) ──
  'Phishing-resistente MFA (Passkeys)',
  'E-Mail-Verschlüsselungs-Einführung',
  'Passwort-Hygiene-Projekt',
  'Datenraum-Einrichtung',
  'Compliance-Paket NIS2',
  'Hinweisgeberschutz-Umsetzung',
  'Verfahrensdokumentation GoBD',
  'Barrierefreiheitserklärung',
  'Website-Rechtscheck',
  'Bild- und Fontlizenz-Audit',
  // ── Media & 3D ──
  'Erklärvideo-Produktion',
  'Produktvideo-Produktion',
  '360°-Rundgang',
  'Drohnenaufnahmen',
  'Podcast-Setup',
  '3D-Modellierung',
  '3D-Druck-Auftrag',
  // ── Archiv, Wissen & Web ──
  'Digitale-Archivierung-Einführung',
  'Scan-Strecken-Einrichtung',
  'Interne Wissensdatenbank',
  'IT-Notfallhandbuch',
  'Onboarding-Handbuch IT',
  'Altsystem-Archivierung',
  'Conversion-Funnel-Aufbau',
  'Online-Kurs-Plattform',
  'Mitgliederbereich-Einführung',
  'Kundenbewertungs-Management',
  'Local-SEO-Paket',
  'ERP-Einführungs-Begleitung',
  // ── Software, Security & Datenschutz (Projekttitel) ──
  'Individualsoftware',
  'Webanwendung / SaaS',
  'API-Integration',
  'System-Modernisierung',
  'Wartung & Support (Kontingent)',
  'IT-Sicherheits-Audit',
  'Penetrationstest',
  'ISMS-Aufbau (ISO 27001)',
  'ISMS-Betreuung (laufend)',
  'IT-Grundschutz-Projekt',
  'NIS2-Umsetzung',
  'Security-Awareness-Programm',
  'Externer Datenschutzbeauftragter (DSB)',
  'DSGVO-Compliance-Projekt',
  'Datenschutz-Managementsystem (DSMS)',
  'KI-Compliance (KI-VO)',
])]

export const POSITION_SUGGESTIONS = [...new Set([
  // Website — Konzeption & Design
  'Konzeption und Wireframing',
  'UI/UX Design und Prototyping',
  'Webdesign (Startseite + Unterseiten)',
  'Responsive Design (Mobile/Tablet/Desktop)',
  'Design-Abstimmung und Revisionen',
  'Erstellung Designvorlage / Mockup',
  // Website — Entwicklung
  'Technische Umsetzung (HTML/CSS/JS)',
  'Frontend-Entwicklung (React)',
  'Frontend-Entwicklung (Next.js)',
  'Backend-Entwicklung (Node.js)',
  'Backend-Entwicklung (Python/FastAPI)',
  'WordPress-Theme-Entwicklung',
  'WordPress-Plugin-Anpassung',
  'CMS-Einrichtung und Konfiguration',
  'Datenbankmodellierung und -einrichtung',
  'API-Entwicklung und Integration',
  'Formularentwicklung mit Validierung',
  'Kontaktformular mit E-Mail-Versand',
  'Buchungssystem-Integration',
  'Zahlungsintegration (Stripe/PayPal)',
  // Content & SEO
  'Content-Einpflege und Formatierung',
  'Bildbearbeitung und -optimierung',
  'Texterstellung und -überarbeitung',
  'SEO-Grundoptimierung (Meta-Tags, Sitemap, robots.txt)',
  'SEO-Analyse und Keyword-Recherche',
  'Google Search Console Einrichtung',
  'Google Analytics / Tag Manager Setup',
  'Strukturierte Daten (Schema.org)',
  // Hosting & Infrastruktur
  'Server-Einrichtung und Konfiguration',
  'Hosting-Migration (inkl. DNS)',
  'SSL-Zertifikat Einrichtung',
  'Domain-Einrichtung und DNS-Konfiguration',
  'E-Mail-Einrichtung (IMAP/SMTP)',
  'Backup-System einrichten',
  'CDN-Konfiguration',
  'Docker-Setup und Deployment',
  'CI/CD Pipeline einrichten',
  'Monitoring und Alerting einrichten',
  // Performance & Sicherheit
  'Performance-Optimierung (Ladezeit)',
  'Bildkomprimierung und Lazy Loading',
  'Caching-Konfiguration',
  'Sicherheitsaudit und Härtung',
  'DSGVO-Anpassung (Cookie-Banner, Datenschutz)',
  'Impressum und Datenschutzerklärung',
  'Sicherheitsupdates einspielen',
  'Malware-Bereinigung',
  'Firewall-Konfiguration',
  // Wartung & Support
  'Monatliche Wartung und Updates',
  'CMS-Updates (Core + Plugins)',
  'Fehlerbehebung / Bugfix',
  'Technischer Support (Remote)',
  'Einweisung / Schulung CMS-Bedienung',
  'Dokumentation der technischen Umsetzung',
  // App & Software
  'App-Konzeption und Planung',
  'Mobile App Entwicklung',
  'Progressive Web App (PWA)',
  'Desktop-Anwendung',
  'Datenbank-Migration',
  'Schnittstellen-Entwicklung (REST/GraphQL)',
  'Automatisierung von Geschäftsprozessen',
  // Beratung
  'Technische Beratung (Erstgespräch)',
  'Anforderungsanalyse',
  'Architektur-Konzeption',
  'Digitalisierungsberatung',
  'Code-Review und Qualitätssicherung',
  'Projektmanagement und Koordination',
  // KI
  'KI-gestützte Entwicklung',
  'KI-API-Kosten',
  'KI-Integration und Konfiguration',
  'Chatbot-Einrichtung',
  'Automatisierung mit KI-Werkzeugen',
  // Vor-Ort / Remote-Support am Kundenrechner
  'Vor-Ort-Service beim Kunden',
  'Remote-Support (TeamViewer/AnyDesk)',
  'Einrichtung Arbeitsplatzrechner',
  'Einrichtung Notebook / Laptop',
  'Windows-Installation und Grundkonfiguration',
  'macOS-Installation und Grundkonfiguration',
  'Windows-Updates einspielen',
  'macOS-Updates einspielen',
  'Treiber-Installation und -Update',
  'Datenmigration auf neuen Rechner',
  'Druckereinrichtung (lokal/Netzwerk)',
  'WLAN-/Netzwerk-Einrichtung',
  'VPN-Einrichtung und Konfiguration',
  // E-Mail-Konfiguration
  'E-Mail-Konto einrichten (Outlook)',
  'E-Mail-Konto einrichten (Apple Mail)',
  'E-Mail-Konto einrichten (Thunderbird)',
  'E-Mail-Konto einrichten (Mobilgerät iOS/Android)',
  'E-Mail-Migration (Konten und Postfächer)',
  'Signatur und Abwesenheitsnotiz einrichten',
  'Spam-/Phishing-Filter konfigurieren',
  // Browser & Software
  'Google Chrome Installation und Einrichtung',
  'Firefox Installation und Einrichtung',
  'Microsoft Edge Konfiguration',
  'Browser-Lesezeichen und Passwort-Import',
  'Office-Paket Installation (Microsoft 365)',
  'Office-Paket Installation (LibreOffice)',
  'PDF-Software Installation (Adobe Reader)',
  'Antivirus-Software Installation',
  'Passwort-Manager Einrichtung',
  // Sicherheit am Kundenrechner
  'Firewall-Einstellungen prüfen und anpassen',
  'Windows Defender / Security prüfen',
  'Sicherheitsüberprüfung Arbeitsplatzrechner',
  'Update-Einstellungen prüfen und optimieren',
  'Datensicherung einrichten (lokal/Cloud)',
  'Cloud-Speicher Setup (OneDrive/Dropbox/iCloud)',
  'Zwei-Faktor-Authentifizierung einrichten',
  'Passwort-Audit und Neuvergabe',
  // Datenrettung & Fehlerdiagnose
  'Datenrettung und Wiederherstellung',
  'Fehlerdiagnose Hardware',
  'Fehlerdiagnose Software',
  'System-Reinigung und Performance-Optimierung',
  'Registry-Bereinigung',
  'Festplatten-Check und Defragmentierung',
  // Recherche & Dokumentation
  'Recherche zu technischem Sachverhalt',
  'Recherche zu rechtlichem Sachverhalt',
  'Recherche und Analyse',
  'Erstellung Recherche-Report',
  'Erstellung Statusbericht',
  'Erstellung Dokumentation / Report',
  'Gutachten / Stellungnahme',
  'Abklärung und Korrespondenz',
  'Vorbereitung Rechtsfall / Sachverhaltsklärung',
  'Bildschirmaufnahmen und Screenshots dokumentiert',
  // Kommunikation & Koordination
  'Telefonat (Beratung/Abstimmung)',
  'Videokonferenz (Beratung/Abstimmung)',
  'E-Mail-Korrespondenz',
  'Abstimmung mit Dienstleistern',
  'Abstimmung mit Behörden',
  // Schulung
  'Schulung E-Mail-Programm',
  'Schulung Office-Anwendungen',
  'Schulung Browser-Nutzung und Sicherheit',
  'Schulung Cloud-Speicher',
  'Schulung allgemeine PC-Nutzung',
  // E-Mail-Administration & Postfächer (Webmaster)
  'E-Mail-Backup aller Postfächer (vollständige Sicherung)',
  'Regelmäßige E-Mail-Sicherung (geplanter Job)',
  'Export einzelner Postfächer (PST/MBOX/EML)',
  'Revisionssichere E-Mail-Archivierung einrichten',
  'Archivierung und Auslagerung alter E-Mails',
  'Wiederherstellung gelöschter E-Mails',
  'Migration Postfächer zu Microsoft 365',
  'Migration Postfächer zu Google Workspace',
  'Einrichtung Microsoft 365 (Tenant)',
  'Einrichtung Google Workspace',
  'Verwaltung E-Mail-Aliase und Verteiler',
  'Einrichtung gemeinsames Postfach (Shared Mailbox)',
  'Einrichtung Catch-All-Postfach',
  'Konfiguration Autoresponder/Abwesenheit (alle Postfächer)',
  'Einrichtung E-Mail-Weiterleitungen',
  'Postfach-Speicherkontingente konfigurieren',
  'Bereinigung überfüllter Postfächer',
  'E-Mail-Zustellbarkeit prüfen und verbessern',
  'Einrichtung SPF-Eintrag',
  'Einrichtung DKIM-Signierung',
  'Einrichtung DMARC-Richtlinie',
  'Konfiguration MX-Einträge (DNS)',
  'Entfernung von E-Mail-Blacklists (Delisting)',
  'Einrichtung E-Mail-Verschlüsselung (S/MIME)',
  'Einrichtung E-Mail-Verschlüsselung (PGP)',
  'Konfiguration Mailserver (Postfix/Dovecot)',
  'Einrichtung Webmail-Oberfläche',
  'Schulung sicherer E-Mail-Umgang',
  // Webmaster & laufende Website-Betreuung
  'Laufende Website-Betreuung (monatlich)',
  'Website-Pflege und Inhaltsaktualisierung',
  'Redaktionelle Betreuung der Website',
  'Pflege von Produkten/Artikeln (Shop)',
  'Aktualisierung von Öffnungszeiten und Kontaktdaten',
  'Einpflege von Blogbeiträgen',
  'Einpflege von Stellenanzeigen',
  'Pflege Veranstaltungskalender',
  'Bildaustausch und Galerie-Aktualisierung',
  'Aktualisierung rechtlicher Texte (AGB/Widerruf)',
  'Linkpflege und Behebung toter Links',
  'Überprüfung und Erneuerung abgelaufener Domains',
  'Domain-Transfer (Provider-Wechsel)',
  'Verwaltung mehrerer Domains (Portfolio)',
  'Verlängerung Hosting- und Domain-Verträge',
  'Wiederherstellung der Website aus Backup',
  'Einrichtung Staging-/Testumgebung',
  'Übertragung Staging auf Live',
  'Pflege Wartungsmodus während Updates',
  'Uptime-Überwachung einrichten',
  'Monatlicher Performance-Report',
  'Monatlicher Wartungsbericht',
  'Monatlicher SEO-Report',
  'Barrierefreiheit prüfen (WCAG)',
  'Barrierefreiheit umsetzen (WCAG 2.1 AA)',
  'Cookie-Consent-Tool aktualisieren',
  'Erneuerung SSL-Zertifikat',
  'Überwachung Zertifikatsablauf',
  // SEO / SEA / Content-Marketing
  'Suchmaschinenoptimierung (laufend, monatlich)',
  'OnPage-SEO-Optimierung',
  'OffPage-SEO und Linkaufbau',
  'Technisches SEO-Audit',
  'Local SEO (Google Unternehmensprofil)',
  'Einrichtung und Pflege Google Unternehmensprofil',
  'Bing Places Eintrag',
  'Branchenbucheinträge pflegen',
  'SEO-Texterstellung (pro Seite)',
  'Lektorat und Korrektorat',
  'Erstellung Content-/Redaktionsplan',
  'Blogartikel-Erstellung (recherchiert)',
  'Erstellung von Landingpages',
  'A/B-Test-Konzeption und Auswertung',
  'Conversion-Optimierung (CRO)',
  'Google Ads Kampagnen-Einrichtung',
  'Google Ads Kampagnen-Betreuung (monatlich)',
  'Microsoft Ads (Bing) Einrichtung',
  'Meta Ads (Facebook/Instagram) Einrichtung',
  'Meta Ads Kampagnen-Betreuung (monatlich)',
  'LinkedIn Ads Einrichtung',
  'Keyword-Recherche und Wettbewerbsanalyse',
  'Erstellung Anzeigentexte und Creatives',
  'Conversion-Tracking einrichten',
  'Retargeting/Remarketing einrichten',
  // Social Media & E-Mail-Marketing
  'Social-Media-Konzept und -Strategie',
  'Einrichtung Social-Media-Profile',
  'Social-Media-Betreuung (monatlich)',
  'Erstellung Social-Media-Content (Posts)',
  'Erstellung Social-Media-Grafiken',
  'Redaktionsplan Social Media',
  'Community-Management',
  'Erstellung Reels/Kurzvideos',
  'YouTube-Kanal-Einrichtung',
  'Video-Schnitt und -Bearbeitung',
  'Newsletter-System einrichten (Mailchimp/Brevo)',
  'Newsletter-Template-Erstellung',
  'Newsletter-Erstellung und -Versand',
  'Aufbau und Pflege Verteilerliste (DSGVO-konform)',
  'Marketing-Automation einrichten',
  'WhatsApp Business einrichten',
  'Erstellung E-Mail-Marketing-Kampagne',
  // Branding, Grafik & Print
  'Logo-Design / Logo-Redesign',
  'Corporate Design / Styleguide',
  'Visitenkarten-Gestaltung',
  'Geschäftsausstattung (Briefpapier etc.)',
  'Flyer-/Broschüren-Gestaltung',
  'Plakat-/Banner-Gestaltung',
  'Rollup-/Messestand-Gestaltung',
  'Erstellung Präsentationsvorlage',
  'Druckdatenaufbereitung (Druckvorstufe)',
  'Produktfotografie und Bildbearbeitung',
  'Erstellung Infografik',
  'Icon- und Illustrationserstellung',
  // DSGVO & Datenschutz
  'DSGVO-Erstberatung',
  'Datenschutz-Audit der Website',
  'Erstellung Verzeichnis von Verarbeitungstätigkeiten (VVT)',
  'Erstellung Datenschutzerklärung (individuell)',
  'Aktualisierung Datenschutzerklärung',
  'Erstellung Auftragsverarbeitungsvertrag (AVV)',
  'Prüfung bestehender AVV',
  'Technisch-organisatorische Maßnahmen (TOM) dokumentieren',
  'Datenschutz-Folgenabschätzung (DSFA)',
  'Cookie-Consent-Management einrichten (TTDSG-konform)',
  'Cookie-Audit und Kategorisierung',
  'DSGVO-Prüfung externer Dienste/Einbindungen',
  'Google Fonts lokal einbinden (DSGVO)',
  'Google Analytics DSGVO-konform konfigurieren',
  'Datenschutzkonformes Tracking einrichten (Matomo)',
  'Umsetzung Betroffenenrechte (Auskunft/Löschung)',
  'Erstellung Lösch- und Aufbewahrungskonzept',
  'Datenschutz-Schulung Mitarbeiter',
  'Unterstützung bei Meldung einer Datenpanne',
  'Double-Opt-In für Newsletter umsetzen',
  'Prüfung Einwilligungsmanagement',
  'Erstellung Hinweise zur Videoüberwachung',
  'Datenschutzhinweise für Bewerber',
  'Datenschutz für Social-Media-Auftritte',
  'Drittland-Transfer prüfen (Standardvertragsklauseln)',
  // Cybersecurity
  'IT-Sicherheitsanalyse / Security-Assessment',
  'Schwachstellen-Scan (extern)',
  'Schwachstellen-Scan (intern)',
  'Penetrationstest (Webanwendung)',
  'Penetrationstest (Netzwerk)',
  'Phishing-Simulation für Mitarbeiter',
  'Security-Awareness-Schulung',
  'Server-Härtung (CIS-Benchmark)',
  'Webserver-Härtung (Nginx/Apache)',
  'Einrichtung Web Application Firewall (WAF)',
  'Einrichtung Intrusion Detection (IDS)',
  'Einrichtung zentrales Logging/SIEM',
  'Notfallplan / Incident-Response-Konzept',
  'Incident Response (akuter Sicherheitsvorfall)',
  'Forensische Analyse nach Sicherheitsvorfall',
  'Ransomware-Vorsorgekonzept',
  'Wiederherstellung nach Ransomware-Angriff',
  'Backup-Strategie (3-2-1) konzipieren',
  'Notfall-Wiederherstellungstest (Disaster Recovery)',
  'Einrichtung verschlüsselter Offsite-Backups',
  'Endpoint-Protection ausrollen',
  'Mobile-Device-Management (MDM) einrichten',
  'Festplattenverschlüsselung (BitLocker/FileVault)',
  'Einrichtung Passwortrichtlinie',
  'Einführung Passwort-Manager (Team)',
  'Einrichtung Single Sign-On (SSO)',
  'Multi-Faktor-Authentifizierung unternehmensweit',
  'TLS-/SSL-Konfiguration härten',
  'Sicherheits-Patch-Management einrichten',
  'Leak-Monitoring kompromittierter Zugangsdaten',
  'Erstellung IT-Sicherheitsrichtlinie',
  'Erstellung Berechtigungskonzept',
  'Zugriffsrechte-Review (Least Privilege)',
  'Netzwerksegmentierung konzipieren',
  'Firewall-Regelwerk-Review',
  'DDoS-Schutz einrichten',
  'Sicherheitsüberprüfung Webshop',
  'Code-Security-Review (statische Analyse)',
  'Dependency-/Abhängigkeits-Audit',
  'WordPress-Härtung (Hardening)',
  'Bereinigung gehackter Website',
  'Wiederherstellung nach Website-Hack',
  'SSL-Labs-Test und Optimierung',
  // IT-Administration & Infrastruktur
  'IT-Betreuung (monatliche Pauschale)',
  'Managed Services (monatlich)',
  'Service-Level-Agreement (SLA) Betreuung',
  'Benutzerverwaltung (Onboarding/Offboarding)',
  'Active Directory / Entra ID Verwaltung',
  'Gruppenrichtlinien (GPO) konfigurieren',
  'Fileserver einrichten und Freigaben verwalten',
  'NAS-Einrichtung und Konfiguration',
  'Netzwerk-Switch-Konfiguration',
  'WLAN-Ausleuchtung und Access-Points',
  'Router-/Firewall-Appliance einrichten',
  'VLAN-Konfiguration',
  'Print-Server-Verwaltung',
  'USV-Einrichtung und Monitoring',
  'Virtualisierung einrichten (Proxmox/VMware)',
  'Container-Orchestrierung (Kubernetes) einrichten',
  'Cloud-Migration (AWS/Azure/Hetzner)',
  'Cloud-Kostenoptimierung',
  'Infrastruktur als Code (Terraform/Ansible)',
  'Monitoring-Dashboard einrichten (Grafana)',
  'Log-Management einrichten',
  'Automatisiertes Backup-Monitoring',
  'Lizenzverwaltung und -beschaffung',
  'Hardware-Beschaffung und -Empfehlung',
  'Inventarisierung IT-Assets',
  // Shop & E-Commerce
  'Onlineshop-Einrichtung (WooCommerce)',
  'Onlineshop-Einrichtung (Shopify)',
  'Produktimport und -pflege',
  'Zahlungsanbieter anbinden',
  'Versandarten und -kosten konfigurieren',
  'Steuer-/MwSt.-Konfiguration im Shop',
  'Anbindung Warenwirtschaft/ERP',
  'Anbindung Buchhaltung (DATEV/lexoffice)',
  'Rechnungs-/Lieferschein-Automatisierung',
  'Gutschein- und Rabattsystem einrichten',
  'Produktdatenfeed (Google Shopping)',
  'Marktplatz-Anbindung (Amazon/eBay)',
  // Daten, Migration & Automatisierung
  'Datenmigration zwischen Systemen',
  'CSV-/Excel-Datenimport',
  'Datenbereinigung und Deduplizierung',
  'Schnittstellen-Anbindung (Zapier/Make)',
  'Webhook-Integration',
  'CRM-Einrichtung und -Anpassung',
  'CRM-Datenmigration',
  'Reporting-Automatisierung',
  'Erstellung Auswertungen / Dashboards',
  'Skript zur Prozessautomatisierung',
  // Schulung & Beratung
  'Workshop (halbtägig)',
  'Workshop (ganztägig)',
  'Schulung Content-Management (Redakteure)',
  'Schulung SEO-Grundlagen',
  'Schulung Social Media',
  'Schulung Datenschutz/DSGVO',
  'Schulung IT-Sicherheit für Mitarbeiter',
  'Schulung Microsoft 365 / Teams',
  'Erstellung Schulungsunterlagen',
  'Erstellung Video-Tutorials',
  'Strategieberatung Online-Marketing',
  'Fördermittelberatung Digitalisierung (z.B. go-digital)',
  // Projekt & Sonstiges
  'Projekt-Setup und Kickoff',
  'Pflichtenheft / Lastenheft erstellen',
  'Ausschreibungsunterstützung',
  'Qualitätssicherung / Testing',
  'Abnahme und Übergabe',
  'Reisezeit / Anfahrt',
  'Express-/Wochenendzuschlag',
  'Bereitschaft / Rufbereitschaft (monatlich)',
  'Dringende Störungsbehebung (Notfall)',
  'Aufwandsabhängige Tätigkeit nach Absprache',
  // ── KI-Automatisierung (celox-Kernportfolio) ──
  'Prozess-Audit und Automatisierungspotenzial-Analyse',
  'Prozessaufnahme und Ist-Analyse',
  'Soll-Prozess-Konzeption (Workflow-Redesign)',
  'Automatisierungs-Roadmap erstellen',
  'Intelligente Dokumentenverarbeitung einrichten',
  'Automatische Rechnungserfassung (Beleg → Buchhaltung)',
  'OCR-Texterkennung einrichten',
  'Automatische Datenextraktion aus PDFs',
  'E-Mail-Klassifizierung und Routing einrichten',
  'Automatische E-Mail-Beantwortung (KI-Entwurf)',
  'Posteingangs-Automatisierung',
  'Individuellen KI-Assistenten konzipieren',
  'KI-Assistent entwickeln und einrichten',
  'KI-Chatbot für Website einrichten',
  'Interne Wissensdatenbank mit KI-Suche (RAG)',
  'RAG-Pipeline einrichten (Dokumente anbinden)',
  'Prompt-Engineering und Optimierung',
  'Prompt-Vorlagen für das Team erstellen',
  'LLM-Integration (Claude API)',
  'LLM-Integration (OpenAI API)',
  'KI-Modell-Auswahl und Evaluierung',
  'KI-Kosten-Optimierung (Caching, Modellwahl)',
  'KI-Guardrails und Qualitätssicherung',
  'KI-Nutzungs-Monitoring einrichten',
  'Automatische Angebotserstellung einrichten',
  'Automatische Berichtserstellung (Reporting)',
  'KPI-Dashboard konzipieren und einrichten',
  'Datenpipeline einrichten (ETL)',
  'Datenaufbereitung und -bereinigung',
  'Automatischer Datenabgleich zwischen Systemen',
  'CRM-Integration und Lead-Scoring',
  'Lead-Erfassung automatisieren',
  'Angebots-Nachverfolgung automatisieren',
  'Terminbuchung automatisieren',
  'Onboarding-Prozess automatisieren',
  'Workflow-Automatisierung (n8n/Make)',
  'Skript-Automatisierung (Python)',
  'Automatisierung wiederkehrender Berichte',
  'Meeting-Transkription und Zusammenfassung einrichten',
  'Sprache-zu-Text-Workflow (Transkription)',
  'Automatische Übersetzung von Inhalten einrichten',
  'Social-Media-Posting automatisieren',
  'Bewerbungseingang automatisiert vorsortieren',
  'Support-Anfragen automatisch kategorisieren',
  'FAQ-Bot aus Bestandsdokumenten erstellen',
  'KI-Schulung für Mitarbeiter (Grundlagen)',
  'KI-Schulung: Sicherer Umgang mit ChatGPT & Co.',
  'Prompt-Workshop für Fachabteilung',
  'KI-Richtlinie für das Unternehmen erstellen',
  'KI-Einsatz DSGVO-konform gestalten (AVV, Datenflüsse)',
  'EU-AI-Act-Ersteinschätzung',
  'Automatisierungs-Betreuung (monatlich)',
  'Pflege und Weiterentwicklung Automatisierungen',
  // ── E-Rechnung, Buchhaltung & ERP ──
  'E-Rechnung-Umstellung (ZUGFeRD/XRechnung)',
  'E-Rechnungs-Eingangsprozess einrichten',
  'E-Rechnungs-Validierung einrichten',
  'DATEV-Export einrichten',
  'Schnittstelle zur Buchhaltung einrichten',
  'Lexoffice-/sevDesk-Integration',
  'GoBD-konforme Ablage konzipieren',
  'Belegarchivierung digitalisieren',
  'Warenwirtschafts-Anbindung (ERP)',
  'Rechnungsfreigabe-Workflow digitalisieren',
  'Mahnwesen automatisieren',
  'Zahlungsabgleich automatisieren (Bank-API)',
  'Kassensystem-Anbindung',
  'Warenbestand-Synchronisation (Shop ↔ ERP)',
  // ── Microsoft 365 & Collaboration ──
  'Microsoft-365-Lizenzberatung und -verwaltung',
  'Microsoft Teams einrichten und strukturieren',
  'SharePoint-Struktur konzipieren und einrichten',
  'OneDrive-Rollout im Team',
  'Exchange-Online-Konfiguration',
  'Microsoft-365-Sicherheitsgrundeinstellungen (Secure Score)',
  'Conditional-Access-Richtlinien einrichten',
  'Intune-Geräteverwaltung einrichten',
  'Microsoft-365-Backup einrichten',
  'Migration Fileserver → SharePoint/OneDrive',
  'Teams-Telefonie einrichten',
  'Power-Automate-Flow erstellen',
  'Outlook-Regeln und QuickSteps einrichten',
  'Intranet-Aufbau (SharePoint)',
  'Wiki/Knowledge-Base einrichten',
  // ── IT-Betrieb & Systemhaus ──
  'IT-Inventarisierung (Hard- und Software)',
  'IT-Dokumentation erstellen/aktualisieren',
  'Netzwerkdokumentation (IP-Plan, Topologie)',
  'Admin-Zugänge dokumentieren und übergeben',
  'Patch-Management einrichten (automatisiert)',
  'Software-Verteilung einrichten',
  'Client-Rollout (Standard-Image)',
  'Hardware-Beschaffung und Beratung',
  'Hardware-Lifecycle-Planung',
  'Zertifizierte Datenlöschung (Altgeräte)',
  'Alt-IT fachgerecht entsorgen (Nachweis)',
  'Helpdesk-/Ticketsystem einrichten',
  'Remote-Monitoring-Agent ausrollen (RMM)',
  'Server-Monitoring einrichten (Zabbix/CheckMK)',
  'Wartungsfenster: Server-Updates einspielen',
  'Hyper-V-Virtualisierung einrichten',
  'VM-Migration (P2V/V2V)',
  'Storage-Erweiterung planen und umsetzen',
  'RAID-Konfiguration und Funktionstest',
  'USV-Test und Batterietausch',
  'Serverraum-Check (Kühlung, Strom, Zugang)',
  'Homeoffice-Arbeitsplatz einrichten (Remote-Zugang)',
  'Remote-Desktop-Server einrichten (RDS)',
  'Terminalserver-Wartung',
  'Standortvernetzung (Site-to-Site-VPN)',
  'Internet-Failover einrichten (Ausfallsicherheit)',
  'VoIP-Telefonanlage einrichten',
  'VoIP-Migration (ISDN-Ablösung)',
  'Konferenzraum-Technik einrichten',
  'Digital-Signage einrichten',
  'IT-Umzug Büro (Planung und Durchführung)',
  'IT-Onboarding neuer Mitarbeiter',
  'IT-Offboarding (Zugänge entziehen, Datenübergabe)',
  'Quartals-Review IT (Jour fixe)',
  'IT-Budgetplanung (Jahresplanung)',
  'Lizenz-Audit (Compliance)',
  'IT-Vertragsübersicht erstellen (Vertragsmanagement)',
  'Provider-Kündigung und Wechselbegleitung',
  'Zweitmeinung / Angebotsprüfung IT',
  'Technische Due Diligence',
  // ── Security & Compliance (NIS2/ISO/BSI) ──
  'NIS2-Betroffenheitsanalyse',
  'NIS2-Umsetzungsbegleitung',
  'ISO-27001-Gap-Analyse',
  'ISMS-Aufbau begleiten (ISO 27001)',
  'IT-Risikoanalyse (BSI 200-3)',
  'IT-Grundschutz-Check (BSI)',
  'IT-Notfallhandbuch erstellen',
  'Business-Continuity-Plan erstellen',
  'Cyber-Versicherung: technische Fragebogen-Begleitung',
  'IT-Sicherheits-Check (Basis-Paket)',
  'Phishing-Simulationskampagne durchführen',
  'Auswertung Phishing-Simulation + Maßnahmenplan',
  'Security-Awareness-Schulung (online, interaktiv)',
  'Security-Awareness-Schulung (vor Ort)',
  'Live-Hacking-Demo für Mitarbeiter',
  'CEO-Fraud-/Deepfake-Sensibilisierung',
  'Passwort-Leak-Prüfung (kompromittierte Konten)',
  'E-Mail-Sicherheits-Audit (SPF/DKIM/DMARC)',
  'Microsoft-365-Security-Audit',
  'Externer Datenschutzbeauftragter (monatliche Pauschale)',
  'Datenschutz-Jahresbericht erstellen',
  'Jährliches Datenschutz-Audit',
  'Verpflichtung auf das Datengeheimnis dokumentieren',
  'Löschkonzept technisch umsetzen (automatisierte Löschung)',
  'Auskunftsersuchen bearbeiten (Art. 15 DSGVO)',
  'Datenschutz-Check neuer Software/Tools',
  // ── Web & App (Ergänzungen) ──
  'Astro-Website-Entwicklung',
  'Web-App-Entwicklung (SPA)',
  'Kundenportal-Entwicklung',
  'Mitgliederbereich mit Login einrichten',
  'Mehrsprachigkeit einrichten (i18n)',
  'Website-Suche einrichten',
  'Blog-Migration (Inhalte übernehmen)',
  'PDF-Generierung einrichten (Rechnungen/Reports)',
  'Web-Push-Benachrichtigungen einrichten',
  'Offline-Fähigkeit (PWA) einrichten',
  'Barrierefreiheits-Audit (BFSG/WCAG)',
  'Android-App-Entwicklung',
  'App-Update im Play Store veröffentlichen',
  'Crash-Analyse und App-Stabilisierung',
  'Terminbuchungssystem einrichten',
  'Umfrage-/Feedback-Tool einrichten',
  'Produktkonfigurator-Entwicklung',
  // ── Cloud & Infrastruktur (Ergänzungen) ──
  'Cloud-Kosten-Analyse und Optimierung',
  'Infrastruktur-/Architektur-Review',
  'Server-Migration (Provider-Wechsel)',
  'Reverse-Proxy einrichten (Nginx)',
  'Docker-Compose-Stack einrichten',
  'Automatisierte Deployments (GitHub Actions)',
  'Secrets-Management einrichten',
  'Datenbank-Replikation einrichten (Hochverfügbarkeit)',
  'Objektspeicher einrichten (S3-kompatibel)',
  'Status-Page und Wartungsseite einrichten',
  'Lasttest und Kapazitätsplanung',
  'Zero-Downtime-Deployment einrichten',
  // ── IoT & Smart Building ──
  'Smart-Home-/Smart-Office-Integration',
  'Raspberry-Pi-Lösung entwickeln',
  'IoT-Sensorik einrichten (Temperatur/Klima)',
  'MQTT-Broker einrichten',
  'Energie-Monitoring einrichten',
  // ── Projekt & Übergabe (Ergänzungen) ──
  'Workshop Prozessdigitalisierung',
  'Workshop Tool-Auswahl (Anforderungsanalyse)',
  'Admin-Schulung (Übergabe an interne IT)',
  'Schulung neue Software (Einführung)',
  'Datenimport aus Altsystem',
  'Altsystem-Ablösung (Legacy-Migration)',
  'Testkonzept und Testdurchführung',
  'Benutzerakzeptanztest begleiten (UAT)',
  'Go-Live-Begleitung',
  'Nachbetreuung nach Go-Live (Hypercare)',
  'Rollback-Plan erstellen',
  'Übergabe-Dokumentation Projektabschluss',
  'Feature-Entwicklung nach Aufwand',
  // ── CMS & Shop-Systeme (konkret) ──
  'WooCommerce-Shop einrichten',
  'WooCommerce-Erweiterung konfigurieren',
  'Shopware-Einrichtung',
  'Shopware-Migration (Versionswechsel)',
  'Shopify-Shop einrichten',
  'Shop-Migration (Plattformwechsel)',
  'TYPO3-Update/-Upgrade',
  'Webflow-Umsetzung',
  'Migration Website-Baukasten → WordPress',
  'Page-Builder-Umsetzung (Elementor)',
  'Rechtstexte-Schnittstelle einrichten (Shop)',
  'Gütesiegel-Integration (Trusted Shops)',
  'Produktdatenpflege (Shop)',
  'Varianten- und Preispflege (Shop)',
  'Zahlungsarten erweitern (Klarna/Mollie)',
  'Versandschnittstelle einrichten (DHL/DPD)',
  'Retouren-Prozess einrichten',
  'Marktplatz-Anbindung (Amazon/eBay)',
  // ── Entwicklung (Ergänzungen) ──
  'Code-Refactoring',
  'Abbau technischer Schulden',
  'Unit-Tests erstellen',
  'Testautomatisierung (E2E) einrichten',
  'Framework-Upgrade (Major-Version)',
  'PHP-Versions-Upgrade',
  'TypeScript-Migration',
  'Legacy-Code-Analyse',
  'Query- und Index-Optimierung (Datenbank)',
  'OAuth-/SSO-Integration (Login mit Google/Microsoft)',
  'Passkey-Login einrichten',
  'Webhook-Integration',
  'CSV-/Excel-Import-Funktion',
  'Export-Funktion (CSV/Excel/PDF)',
  'Volltextsuche einrichten (Elasticsearch/Meilisearch)',
  'Karten-/Geodaten-Integration',
  'Kalender-Integration (iCal/Google)',
  'E-Signatur-Integration',
  'Echtzeit-Funktionen (WebSocket)',
  'Mandantenfähigkeit implementieren',
  'Rollen- und Rechtesystem implementieren',
  'Audit-Log implementieren',
  // ── KI (Ergänzungen) ──
  'Vektor-Datenbank einrichten (pgvector/Qdrant)',
  'Embedding-Pipeline einrichten',
  'Lokales LLM einrichten (Ollama)',
  'KI-Datenschutz: Anonymisierung/Pseudonymisierung',
  'KI-Bildgenerierung einrichten',
  'Text-to-Speech einrichten',
  'Whisper-Transkription einrichten',
  'KI-Telefonassistent einrichten (Voice-Bot)',
  'Chatbot-Wissensbasis pflegen',
  'KI-Antwortqualität evaluieren (Testset)',
  'KI-Agent für Rechercheaufgaben einrichten',
  'Batch-Verarbeitung mit KI (Massendaten)',
  'Datenaufbereitung für KI-Anbindung',
  'A/B-Test von Prompts',
  'KI-Kostenreport erstellen',
  // ── Daten & Business Intelligence ──
  'Datenanalyse und Auswertung',
  'Power-BI-Bericht erstellen',
  'Looker-Studio-Dashboard erstellen',
  'Excel-Automatisierung (Makros/Power Query)',
  'Google-Sheets-Automatisierung',
  'SQL-Auswertungen erstellen',
  'Datenbereinigung CRM-/Adressdaten',
  'Dubletten-Bereinigung Datenbestand',
  'Datenvisualisierung erstellen',
  // ── Netzwerk & Vor-Ort (Ergänzungen) ──
  'Netzwerkverkabelung (Patchfeld/Dosen)',
  'Serverschrank einrichten (Rack)',
  'PoE-Switch-Installation',
  'Access-Point-Montage und Einrichtung',
  'Gäste-WLAN einrichten (Captive Portal)',
  'Mesh-WLAN einrichten',
  'Videoüberwachung einrichten (Kameras)',
  'Türsprechanlage/Zutrittskontrolle anbinden',
  'Netzwerk-Fehlersuche (Latenz/Paketverlust)',
  'Internet-Leitungswechsel begleiten',
  'Glasfaser-Umstellung begleiten',
  // ── Apple, Linux & Clients ──
  'Mac-Administration',
  'Apple Business Manager einrichten',
  'MDM für Apple-Geräte (Jamf/Mosyle)',
  'Linux-Server-Administration',
  'Linux-Desktop-Einrichtung',
  'Shell-/PowerShell-Skript erstellen',
  'Windows-Autopilot-Einrichtung',
  'Standard-Softwarepaket definieren (Baseline)',
  'Browser-Richtlinien unternehmensweit ausrollen',
  // ── Google Workspace ──
  'Google-Workspace-Administration',
  'Gmail-Migration',
  'Google-Kalender-Freigaben einrichten',
  'Google-Drive-Struktur einrichten',
  // ── Tools & Zusammenarbeit ──
  'Slack-Workspace einrichten',
  'Terminbuchungs-Tool einrichten (Calendly/Cal.com)',
  'Projektmanagement-Tool einführen (Asana/Jira)',
  'Zeiterfassungs-Tool einführen',
  'CRM-Datenpflege',
  'Digitale Unterschriftenlösung einführen',
  // ── Media & 3D ──
  'Erklärvideo erstellen',
  'Produktvideo erstellen',
  'Imagefilm-Begleitung',
  'Drohnenaufnahmen (Außenaufnahmen)',
  '360°-Rundgang erstellen',
  'Podcast-Setup einrichten',
  'Audio-Nachbearbeitung',
  '3D-Modellierung',
  '3D-Druck (Prototyp/Kleinserie)',
  // ── Compliance (Ergänzungen) ──
  'Hinweisgeberschutz-Meldestelle einrichten',
  'Verfahrensdokumentation (GoBD) erstellen',
  'Barrierefreiheitserklärung erstellen',
  'Impressum-Prüfung und Aktualisierung',
  'Website-Rechtscheck (Abmahnrisiken)',
  'Lizenz-Prüfung Bilder/Fonts',
  'Open-Source-Lizenz-Prüfung',
  // ── Managed Services & Betrieb ──
  'Managed Server (monatlich, pro Server)',
  'Managed Client (monatlich, pro Arbeitsplatz)',
  'Managed Firewall (monatlich)',
  'Managed Backup (monatlich)',
  'Managed Antivirus/EDR (monatlich)',
  'SLA-Report erstellen (monatlich)',
  'Patchday-Durchführung (monatlich)',
  'Testrücksicherung durchführen (Backup-Probe)',
  'Notfallübung durchführen (Tabletop)',
  'Ersatzgeräte-Pool verwalten',
  'Garantie-/RMA-Abwicklung',
  'Asset-Etikettierung und Inventur',
  'Störungsanalyse mit Ursachenbericht',
  'Eskalation beim Herstellersupport begleiten',
  'Second-Level-Support für interne IT',
  // ── Archiv & Wissen ──
  'Digitale Archivierung einrichten',
  'Scan-Strecke einrichten (Papier → digital)',
  'OCR-Volltext-Archiv einrichten',
  'Altsystem-Daten archivieren (Abschaltung)',
  'Interne Wissensdatenbank aufbauen',
  'IT-Onboarding-Handbuch erstellen',
  'IT-Notfallkarte für Mitarbeiter erstellen',
  // ── Softwareentwicklung (Detailleistungen) ──
  'Individualsoftware-Entwicklung',
  'Webanwendung (SaaS) entwickeln',
  'REST-/GraphQL-API entwickeln',
  'Schnittstelle/Integration entwickeln',
  'Legacy-System-Modernisierung',
  'Datenbankmodell entwerfen',
  'Datenmigration alt → neu',
  'Automatisierte Tests aufbauen (Testabdeckung)',
  'CI/CD-Pipeline einrichten',
  'Docker-Containerisierung',
  'Code-Refactoring / technische Schuld',
  'Performance-Optimierung (Backend)',
  'Lasttest / Skalierbarkeitsanalyse',
  'Fehlermonitoring einrichten (Sentry)',
  'Quellcode-Übergabe & Einarbeitung',
  'Technische Dokumentation erstellen',
  'Proof of Concept / Prototyp',
  'Wartung & Weiterentwicklung (Kontingent)',
  // ── IT-Sicherheit (Ergänzungen) ──
  'Schwachstellenscan (extern/intern)',
  'Penetrationstest-Retest',
  'Berechtigungskonzept erstellen',
  'Notfallübung / Tabletop-Exercise',
  'Dienstleister-Sicherheitsbewertung',
  'Managementbewertung ISMS begleiten',
  'Internes ISO-27001-Audit durchführen',
  // ── Datenschutz (Ergänzungen) ──
  'Datenschutz-Folgenabschätzung (DSFA)',
  'Datenpannen-Meldeprozess einrichten',
  'Löschkonzept mit Löschfristen erstellen',
  'KI-Nutzung datenschutzkonform einführen',
  'Drittland-Transfer-Prüfung (SCC/TIA)',
  // ── DSMS (datenschutz.celox.io) ──
  'DSMS-Einführung (datenschutz.celox.io)',
  'Datenschutz-Managementsystem – Einrichtung & Onboarding',
  'DSMS-Mandant anlegen & konfigurieren',
  'VVT-Ersterfassung im DSMS',
  'DSMS-Schulung für den Mandanten',
  'DSMS – Monatliche Betreuung & Pflege',
])]

// Rabatt-Begründungen (Rechnungsformular). Dedup via Set.
export const DISCOUNT_REASON_SUGGESTIONS = [...new Set([
  // Bestand (ursprüngliche Liste)
  'Treuerabatt',
  'Erstkundenrabatt',
  'Mengenrabatt',
  'Projektrabatt',
  'Sonderkonditionen',
  'Langfristige Zusammenarbeit',
  'Empfehlungsrabatt',
  'Non-Profit / Verein',
  'Vorkasse-Rabatt',
  'Paketpreis',
  'Frühbucherrabatt',
  'Nachlass wegen Verzögerung',
  'Kulanz',
  'Bestandskundenrabatt',
  'Jubiläumsrabatt',
  // ── Beziehung & Kundenbindung ──
  'Freundschaftsrabatt',
  'Familienrabatt',
  'Freunde-und-Familie-Konditionen',
  'Nachbarschaftsrabatt',
  'Kollegenrabatt',
  'Netzwerkrabatt',
  'Stammkundenrabatt',
  'VIP-Kundenrabatt',
  'Wiederkehrender Kunde',
  'Rückkehrer-Rabatt (Comeback)',
  'Treuebonus (5 Jahre Zusammenarbeit)',
  'Treuebonus (10 Jahre Zusammenarbeit)',
  'Langjährige Partnerschaft',
  'Dankeschön für Vertrauen',
  'Dankeschön für Geduld',
  'Dankeschön für Flexibilität',
  'Erster gemeinsamer Auftrag',
  'Guter Draht / unkomplizierte Zusammenarbeit',
  // ── Akquise & Vertrieb ──
  'Neukundenrabatt',
  'Willkommensrabatt',
  'Kennenlernrabatt',
  'Einführungsrabatt',
  'Einführungspreis neues Angebot',
  'Pilotkundenrabatt',
  'Pilotprojekt-Konditionen',
  'Proof-of-Concept-Konditionen',
  'Referenzkundenrabatt',
  'Referenzprojekt (Case Study erlaubt)',
  'Testimonial-Rabatt (Kundenstimme)',
  'Logo-Nutzung als Referenz erlaubt',
  'Beta-Tester-Rabatt',
  'Early-Adopter-Rabatt',
  'Erstes Projekt in neuer Branche',
  'Portfolio-Projekt',
  'Messerabatt',
  'Event-Aktion',
  'Aktionsrabatt',
  'Kampagnenrabatt',
  'Saisonrabatt',
  'Sommeraktion',
  'Jahresendaktion',
  'Neujahrsaktion',
  'Black-Friday-Aktion',
  'Weihnachtsrabatt',
  'Osteraktion',
  'Feiertagsaktion',
  'Gutschein eingelöst',
  'Gutschein-Code (Aktion)',
  'Gewinnspiel-Gewinn',
  'Social-Media-Aktion',
  'Newsletter-Aktion',
  'Website-Launch-Aktion',
  // ── Volumen, Paket & Laufzeit ──
  'Volumenrabatt',
  'Staffelpreis (Menge)',
  'Rahmenvertragskonditionen',
  'Jahresvertrag-Rabatt',
  'Laufzeitrabatt (12 Monate)',
  'Laufzeitrabatt (24 Monate)',
  'Bundle-Rabatt',
  'Kombipaket Website + Wartung',
  'Kombipaket Hosting + Pflege',
  'Kombipaket Entwicklung + Support',
  'Mehrere Standorte',
  'Mehrere Domains/Projekte',
  'Mehrplatz-/Team-Rabatt',
  'Folgeauftrag-Rabatt',
  'Anschlussauftrag',
  'Zweitprojekt-Rabatt',
  'Parallelprojekt-Rabatt',
  'Gesamtprojekt-Rabatt',
  'Sammelbeauftragung',
  'Vorab gebuchtes Stundenkontingent',
  'Kontingent-Konditionen',
  'Wartungsvertrag inklusive Rabatt',
  'Upgrade auf größeres Paket',
  'Cross-Selling-Rabatt',
  // ── Zahlung & Konditionen ──
  'Skonto (Zahlung binnen 7 Tagen)',
  'Skonto (Zahlung binnen 14 Tagen)',
  'Skonto 2 %',
  'Skonto 3 %',
  'Vorauszahlungsrabatt',
  'Anzahlungsrabatt',
  'Sofortzahler-Rabatt',
  'Barzahlungsrabatt',
  'Jahreszahlung statt monatlicher Zahlung',
  'SEPA-Lastschrift-Rabatt',
  'Dauerauftrag eingerichtet',
  'Zahlungsziel verkürzt',
  'Keine Teilzahlungen nötig',
  // ── Kulanz & Ausgleich ──
  'Kulanznachlass',
  'Kulanz nach Reklamation',
  'Nachlass wegen Mängeln',
  'Nachlass wegen Terminverschiebung',
  'Nachlass wegen Lieferverzug',
  'Entschädigung für Ausfallzeit',
  'Ausgleich für Unannehmlichkeiten',
  'Nachbesserung ohne Berechnung',
  'Fehlerbehebung auf Kulanz',
  'Wartezeit ausgeglichen',
  'Kommunikationsfehler ausgeglichen',
  'Einmaliger Sondernachlass',
  'Härtefallregelung',
  'Preisnachlass nach Absprache',
  'Goodwill-Geste',
  // ── Zielgruppen ──
  'Gemeinnützige Organisation',
  'Non-Profit-Rabatt',
  'Vereinsrabatt',
  'Stiftungsrabatt',
  'Ehrenamts-Rabatt',
  'Sozialrabatt',
  'Bildungsrabatt',
  'Schul-/Kita-Rabatt',
  'Hochschulrabatt',
  'Studierendenrabatt',
  'Azubi-Rabatt',
  'Start-up-Rabatt',
  'Gründerrabatt',
  'Existenzgründer-Konditionen',
  'Kleinunternehmer-Rabatt',
  'Solo-Selbstständigen-Rabatt',
  'Familienbetrieb-Rabatt',
  'Kirchengemeinde-Rabatt',
  'Öffentlicher Sektor (Rahmenkonditionen)',
  'Behörden-Konditionen',
  'Praxis-/Kanzlei-Sonderkonditionen',
  'Handwerker-Kollegenrabatt',
  'Künstler-/Kreativ-Rabatt',
  'Lokales Unternehmen (Kiez-Rabatt)',
  'Regionaler Partner',
  // ── Partner & Wiederverkauf ──
  'Agentur-Rabatt (Wiederverkäufer)',
  'Reseller-Konditionen',
  'White-Label-Konditionen',
  'Subunternehmer-Konditionen',
  'Partneragentur-Rabatt',
  'Kooperationsrabatt',
  'Geschäftspartner-Konditionen',
  'Lieferanten-Gegengeschäft',
  'Barter-Deal (Leistung gegen Leistung)',
  'Sponsoring-Nachlass',
  'Vereinssponsoring',
  'Community-Projekt',
  'Open-Source-Beitrag',
  'Pro-Bono-Anteil',
  // ── Empfehlung & Marketing ──
  'Empfehlungsbonus',
  'Weiterempfehlung ausgesprochen',
  'Vermittlungsbonus',
  'Affiliate-Konditionen',
  'Google-Bewertung hinterlassen',
  'Bewertung auf Bewertungsportal',
  'Teilnahme an Interview/PR',
  'Content-Kooperation',
  'Gegenseitige Verlinkung',
  'Newsletter-Erwähnung',
  'Social-Media-Erwähnung',
  // ── Projekt & Verhandlung ──
  'Preisverhandlung (Einigung)',
  'Angebotsanpassung nach Verhandlung',
  'Budgetobergrenze des Kunden',
  'Budgetanpassung',
  'Wettbewerbsangebot ausgeglichen (Preismatch)',
  'Bestandsschutz alter Preis',
  'Preisgarantie eingehalten',
  'Übergangsrabatt nach Preiserhöhung',
  'Altkunden-Konditionen',
  'Vertragsverlängerungs-Rabatt',
  'Wechselbonus (von Wettbewerber)',
  'Migrationsrabatt (Systemwechsel)',
  'Ablösung Altsystem',
  'Festpreis statt Aufwand',
  'Pauschalpreis-Vorteil',
  'Geringerer Umfang als angeboten',
  'Reduzierter Leistungsumfang',
  'Teilleistung entfallen',
  'Eigenleistung des Kunden',
  'Kunde liefert Inhalte selbst',
  'Kunde übernimmt Testing',
  'Do-it-together-Rabatt (Mitarbeit Kunde)',
  'Flexible Terminplanung möglich',
  'Keine Deadline (niedrige Priorität)',
  'Auslastungsrabatt (ruhige Saison)',
  'Junior-Stundensatz vereinbart',
  'Remote statt vor Ort',
  'Anfahrt inklusive',
  'Erstgespräch auf Auftrag angerechnet',
  'Beratung auf Auftrag angerechnet',
  'Angebot-zu-Auftrag-Bonus',
  'Schulung inklusive',
  'Dokumentation inklusive',
  'Kleinauftrag ohne Grundpauschale',
  'Rundung des Rechnungsbetrags',
  'Centbeträge erlassen',
  // ── Anlässe ──
  'Firmenjubiläum des Kunden',
  'Eigenes Firmenjubiläum',
  'Geburtstagsrabatt',
  'Neueröffnungs-Rabatt',
  'Geschäftsübernahme-Rabatt',
  'Umzugsrabatt',
  'Meilenstein-Dankeschön',
  '100. Auftrag / Jubiläumsauftrag',
  'Weihnachtsgeschenk an Kunden',
  'Jahresabschluss-Dankeschön',
  // ── Klassische Rabattarten (BWL) ──
  'Funktionsrabatt (Kunde übernimmt Aufgaben)',
  'Naturalrabatt (Zusatzleistung statt Nachlass)',
  'Jahresbonus (Umsatzbonus)',
  'Umsatzstaffel erreicht',
  'Saisonrabatt (Nebensaison)',
  'Einführungspreis (Neuprodukt)',
  'Auslaufkonditionen (Angebot endet)',
  'Listenpreis-Anpassung',
  'Sonderpreis laut Angebot',
  'Preis laut Rahmenvertrag',
  'Konditionen laut Partnervertrag',
  // ── Zahlung (Ergänzungen) ──
  'Skonto 1 %',
  'Skonto 5 %',
  'Zahlung bei Abnahme',
  'Komplettzahlung im Voraus',
  // ── Service-Level & Ausgleich ──
  'SLA-Gutschrift (Reaktionszeit verfehlt)',
  'Downtime-Kompensation',
  'Ausfall-Gutschrift',
  'Wiedergutmachung',
  // ── Effizienz weitergegeben (celox-typisch) ──
  'KI-Effizienzvorteil weitergegeben',
  'Automatisierungsvorteil weitergegeben',
  'Wiederverwendung bestehender Komponenten',
  'Standardlösung statt Individualentwicklung',
  'Vorlage/Template genutzt',
  'Aufwand geringer als kalkuliert',
  'Einkaufsvorteil weitergegeben',
  'Hardware zum Einkaufspreis',
  'Sammelbestellung Hardware',
  'Trade-In (Altgeräte in Zahlung)',
  // ── Programme & Förderung ──
  'Kunde-wirbt-Kunde-Programm',
  'Empfehlungsprogramm-Bonus',
  'Partnerprogramm-Konditionen',
  'Einkaufsgemeinschaft/Verbund',
  'Förderprogramm angerechnet (go-digital)',
  'BAFA-Förderanteil berücksichtigt',
  'Digitalisierungszuschuss angerechnet',
  // ── Guthaben & Verrechnung ──
  'Guthaben verrechnet',
  'Überzahlung verrechnet',
  'Gutschrift aus Vormonat verrechnet',
  'Restguthaben Kontingent angerechnet',
  'Anzahlung angerechnet',
  // ── Testphase & Einstieg ──
  'Erster Monat kostenlos (Testphase)',
  'Testphase verlängert',
  'Demo-Phase angerechnet',
  // ── Beziehung (Ergänzungen) ──
  'Inflationsausgleich geteilt',
  'Treue trotz Preiserhöhung',
  'Mehrjahresvertrag (36 Monate)',
  'Vertragsverlängerung vor Ablauf',
  'Mitarbeiterrabatt',
  'Ehemaliger-Kollege-Rabatt',
  'Alumni-Rabatt',
  'Coworking-Community-Rabatt',
  'Vereinsmitglieder-Rabatt',
  // ── Gegenleistung (Ergänzungen) ──
  'Feedback-/Pilotinterview gegeben',
  'Fallstudien-Video-Teilnahme',
  'Beta-Feedback geliefert',
  'Schulungsteilnahme als Referenz',
  // ── Betrag & Abrechnung ──
  'Rundung auf glatten Betrag',
  'Restbetrag erlassen',
  'Bagatellbetrag erlassen',
])]

interface Props {
  /** Für <label htmlFor> — sonst generiert die Komponente keine ID. */
  id?: string
  label?: string
  name: string
  value: string
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  required?: boolean
  placeholder?: string
  suggestions?: string[]
  /** Taxonomie-Feld-Key (role/source/branche/…): lädt Vorschläge hybrid vom
   *  Server (kuratiert ∪ eigene Bestandswerte) und zeigt sie schon bei Fokus. */
  field?: string
  className?: string
  compact?: boolean
  disabled?: boolean
}

/** Match-Hervorhebung: case-insensitiver Substring; kein Treffer → Rohtext. */
function Highlight({ text, query }: { text: string; query: string }) {
  const q = query.trim()
  if (!q) return <>{text}</>
  const idx = text.toLowerCase().indexOf(q.toLowerCase())
  if (idx === -1) return <>{text}</>
  return (
    <>
      {text.slice(0, idx)}
      <mark className="bg-transparent text-accent font-semibold">{text.slice(idx, idx + q.length)}</mark>
      {text.slice(idx + q.length)}
    </>
  )
}

export default function AutocompleteInput({ id, label, name, value, onChange, required, placeholder, suggestions, field, className, compact, disabled }: Props) {
  const [box, setBox] = useState<ComboboxState>(initialCombobox)
  const [remote, setRemote] = useState<string[] | null>(null)
  const wrapperRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)
  const listId = useId()

  // Hybrid-Pool: Server-Taxonomie (field) vor statischem Prop vor Titel-Default.
  useEffect(() => {
    if (!field) return
    getSuggestions(field).then((s) => setRemote(s.values)).catch(() => {})
  }, [field])
  const pool = (field && remote) || suggestions || TITLE_SUGGESTIONS

  // field-Modus zeigt Top-Vorschläge schon bei leerem Feld (kleine kuratierte Listen).
  const filtered = (field || value.length >= 1) ? rankSuggestions(pool, value, 8) : []

  const openWith = (count: number, open = true) => setBox((s) => optionsChanged(s, count, open))
  useEffect(() => {
    // Optionen ändern sich mit der Eingabe → Reducer synchron halten (offen lassen).
    setBox((s) => (s.open ? optionsChanged(s, filtered.length) : { ...s, count: filtered.length }))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, pool.length])

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        setBox((s) => ({ ...s, open: false, activeIndex: -1 }))
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  const handleSelect = (suggestion: string) => {
    const syntheticEvent = {
      target: { name, value: suggestion },
    } as React.ChangeEvent<HTMLInputElement>
    onChange(syntheticEvent)
    setBox((s) => ({ ...s, open: false, activeIndex: -1 }))
    inputRef.current?.focus()
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    const { state, action } = comboboxKeydown(box, e.key)
    if (action === 'select' && box.activeIndex >= 0) {
      e.preventDefault()
      handleSelect(filtered[box.activeIndex])
      return
    }
    if (state !== box) {
      if (e.key !== 'Tab') e.preventDefault()   // Tab darf den Fokus weiterreichen
      setBox(state)
    }
  }

  const open = box.open && filtered.length > 0

  return (
    <div ref={wrapperRef} className={`relative ${className || ''}`}>
      {label && (
        <label className="block text-xs text-text-muted mb-2">
          {label}
          {required && <span className="text-danger ml-1">*</span>}
        </label>
      )}
      <input
        ref={inputRef}
        type="text"
        name={name}
        value={value}
        onChange={(e) => {
          onChange(e)
          openWith(filtered.length || 1)
        }}
        onFocus={() => { if (field || value.length >= 1) openWith(filtered.length) }}
        onKeyDown={handleKeyDown}
        required={required}
        disabled={disabled}
        placeholder={placeholder}
        id={id}
        className={compact ? 'w-full text-sm' : 'w-full'}
        autoComplete="off"
        role="combobox"
        aria-expanded={open}
        aria-autocomplete="list"
        aria-controls={listId}
        aria-activedescendant={box.activeIndex >= 0 ? `${listId}-opt-${box.activeIndex}` : undefined}
      />
      {/* Screenreader-Ansage der Trefferanzahl */}
      <span className="sr-only" aria-live="polite">
        {open ? `${filtered.length} Vorschläge verfügbar` : ''}
      </span>
      {open && (
        <div
          id={listId}
          role="listbox"
          className="absolute z-50 top-full left-0 right-0 mt-1 bg-surface border border-border rounded-lg shadow-lg overflow-hidden max-h-64 overflow-y-auto"
        >
          {filtered.map((s, i) => (
            <button
              key={s}
              id={`${listId}-opt-${i}`}
              role="option"
              aria-selected={i === box.activeIndex}
              type="button"
              onMouseDown={(e) => e.preventDefault()}
              onClick={() => handleSelect(s)}
              className={`w-full text-left px-3 py-2 text-sm transition-colors ${
                i === box.activeIndex
                  ? 'bg-accent/20 text-accent'
                  : 'text-text hover:bg-surface-2'
              }`}
            >
              <Highlight text={s} query={value} />
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
