"""Zentrale Taxonomie für App-weite Autocomplete-Vorschläge (hybrid).

EINE kanonische Quelle: kuratierte deutsche Listen pro Feld-Key + Synonym-Mapping
auf die kanonische Schreibweise. Der Suggestions-Endpoint mischt die kuratierten
Werte mit den eigenen Bestandswerten des Owners (DISTINCT, häufigkeitssortiert).

Alle Funktionen hier sind rein (kein DB-Zugriff) → DB-frei testbar.
"""
from __future__ import annotations

import unicodedata

# --------------------------------------------------------------------------- #
#  Kuratierte Listen (alphabetisch je Kategorie, dedupliziert via dict.fromkeys)
# --------------------------------------------------------------------------- #

_ROLE = [
    # ── Leitung / Inhaberschaft ──
    "Geschäftsführung",
    "Inhaber/in",
    "Vorstand",
    "Gesellschafter/in",
    "Prokurist/in",
    "Partner/in",
    "Betriebsleitung",
    "Niederlassungsleitung",
    "Filialleitung",
    "Kanzleileitung",
    "Praxisleitung",
    "Werkstattleitung",
    # ── IT / Technik ──
    "IT-Leitung",
    "CTO",
    "CIO",
    "CISO",
    "IT-Administrator/in",
    "IT-Sicherheitsbeauftragte/r",
    "Datenschutzbeauftragte/r",
    "Technische Leitung",
    "Leitung Digitalisierung",
    "Softwareentwickler/in",
    "Systemadministrator/in",
    # ── Kaufmännisch ──
    "CFO",
    "COO",
    "Kaufmännische Leitung",
    "Leitung Buchhaltung",
    "Leitung Controlling",
    "Leitung Finanzen",
    "Office Management",
    "Assistenz der Geschäftsführung",
    # ── Marketing / Vertrieb ──
    "Marketing-Leitung",
    "Vertriebsleitung",
    "Leitung E-Commerce",
    "Leitung Kommunikation",
    "Projektleitung",
    "Produktmanagement",
    # ── HR / Verwaltung ──
    "Personalleitung",
    "Leitung Einkauf",
    "Leitung Qualitätsmanagement",
    "Verwaltungsleitung",
]

_SOURCE = [
    # ── Aktive Akquise ──
    "Kaltakquise Telefon",
    "Kaltakquise E-Mail",
    "Kaltakquise vor Ort",
    "LinkedIn",
    "LinkedIn-Import",
    "XING",
    # ── Automatisiert / Recherche ──
    "KI-Recherche",
    "OpenStreetMap",
    "Google Places",
    "Recherche",
    "Branchenverzeichnis",
    "Google Maps",
    # ── Inbound ──
    "Website-Anfrage",
    "Kontaktformular",
    "Newsletter",
    "Google-Suche (Inbound)",
    "Social Media",
    # ── Netzwerk / Persönlich ──
    "Empfehlung",
    "Empfehlung Bestandskunde",
    "Empfehlung Partner",
    "Bestandskunde",
    "Netzwerk-Event",
    "Messe",
    "IHK-Veranstaltung",
    "BNI / Unternehmernetzwerk",
    "Meetup / Konferenz",
    "Stammtisch",
    "Persönlicher Kontakt",
    "Ehemaliger Kollege",
    "Ausschreibung",
    "Ausschreibungsplattform",
    "Freelancer-Plattform",
]

_BRANCHE = [
    # ── Beratung / Recht / Finanzen ──
    "Steuerberater",
    "Wirtschaftsprüfer",
    "Rechtsanwalt",
    "Notariat",
    "Unternehmensberatung",
    "Finanzberater",
    "Versicherungsmakler",
    "Immobilienmakler",
    "Hausverwaltung",
    "Facility Management",
    # ── Gesundheit / Soziales ──
    "Arztpraxis",
    "Zahnarztpraxis",
    "Physiotherapie",
    "Apotheke",
    "Pflegedienst",
    "Kita / Kindergarten",
    "Bildungsträger",
    "Verein / Non-Profit",
    # ── Handwerk / Bau ──
    "Handwerksbetrieb",
    "Bauunternehmen",
    "Elektroinstallation",
    "Sanitär / Heizung / Klima",
    "Schreinerei / Tischlerei",
    "Malerbetrieb",
    "Dachdeckerei",
    "Gebäudereinigung",
    "Garten- und Landschaftsbau",
    "Architekturbüro",
    "Ingenieurbüro",
    # ── Handel / Gastronomie ──
    "Einzelhandel",
    "Großhandel",
    "E-Commerce / Onlineshop",
    "Gastronomie",
    "Hotellerie",
    "Bäckerei",
    "Autohaus",
    "KFZ-Werkstatt",
    # ── Industrie / Logistik ──
    "Maschinenbau",
    "Fertigung / Produktion",
    "Logistik / Spedition",
    "Landwirtschaft",
    # ── Dienstleistung / Digital ──
    "Agentur / IT-Dienstleister",
    "Werbeagentur",
    "Softwareunternehmen",
    "Personaldienstleister",
    "Reinigungsunternehmen",
    "Sicherheitsdienst",
    "Fahrschule",
    "Fitnessstudio",
    "Friseursalon",
    "Kosmetikstudio",
    "Fotostudio",
    "Eventagentur",
    "Reisebüro",
]

# Lead-Tags = Branchen + Qualifizierer (Board-Filter, Kampagnen)
_TAG = list(dict.fromkeys([
    *_BRANCHE[:20],
    # ── Qualifizierer ──
    "Bestandskunde",
    "Neukunde",
    "lokal",
    "Berlin",
    "deutschlandweit",
    "Webshop",
    "WordPress",
    "Kleinunternehmen",
    "Mittelstand",
    "Konzern",
    "Premium",
    "Preissensibel",
    "Warmkontakt",
    "Kaltkontakt",
    "Wiedervorlage",
    "Security-Interesse",
    "DSGVO",
    "KI-Automatisierung",
    "Website-Relaunch",
    "Wartungsvertrag",
    "Empfehlungsgeber",
    "Multiplikator",
]))

_ZIELSYSTEM = [
    # ── Buchhaltung / Steuer ──
    "DATEV",
    "DATEV Unternehmen online",
    "Lexware",
    "lexoffice",
    "sevDesk",
    "BuchhaltungsButler",
    "Candis",
    "GetMyInvoices",
    # ── ERP ──
    "SAP Business One",
    "Microsoft Dynamics 365",
    "Microsoft Dynamics NAV / Business Central",
    "Odoo",
    "weclapp",
    "Xentral",
    "JTL-Wawi",
    "plentymarkets",
    "Sage 100",
    "Sage 50",
    # ── CRM ──
    "HubSpot",
    "Salesforce",
    "Pipedrive",
    "Zoho CRM",
    "CentralStationCRM",
    # ── Office / Kollaboration ──
    "Microsoft 365",
    "SharePoint",
    "Google Workspace",
    "Nextcloud",
    "Notion",
    "Confluence",
    # ── Branchen-Software ──
    "Immoware24",
    "DOMUS",
    "Haufe PowerHaus",
    "Praxissoftware (PVS)",
    "Kanzleisoftware (RA-MICRO)",
    "Handwerkersoftware (Mos'aik)",
    # Entwicklung / Betrieb
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Azure DevOps",
    "Docker",
    "Kubernetes",
    "Proxmox",
    "AWS",
    "Microsoft Azure",
    "Google Cloud Platform",
    "Hetzner Cloud",
    "IONOS",
    "Cloudflare",
    "Vercel",
    "Netlify",
    "WordPress",
    "TYPO3",
    "Shopware",
    "Sentry",
    "Grafana",
    "Prometheus",
    "Uptime Kuma",
    # IT-Sicherheit / Datenschutz
    "Microsoft Defender",
    "Microsoft Intune",
    "Nessus",
    "OpenVAS / Greenbone",
    "Burp Suite",
    "Metasploit",
    "KeePass",
    "Bitwarden",
    "1Password",
    "Veeam Backup",
    "Wazuh (SIEM)",
    "audius:DSMS",
    "DataGuard",
    "Proliance (DSMS)",
    "OneTrust",
    "otris privacy",
    "Usercentrics (CMP)",
    "Cookiebot",
]

_VENDOR = [
    # ── Hosting / Cloud ──
    "Hetzner",
    "IONOS",
    "Strato",
    "netcup",
    "all-inkl",
    "Hostinger",
    "AWS",
    "Google Cloud",
    "Microsoft Azure",
    "DigitalOcean",
    "Cloudflare",
    "Vercel",
    "Netlify",
    # ── Software / SaaS ──
    "Microsoft 365",
    "Google Workspace",
    "Adobe",
    "JetBrains",
    "GitHub",
    "GitLab",
    "Atlassian",
    "Notion",
    "Slack",
    "Zoom",
    "1Password",
    "Bitwarden",
    "Figma",
    "Sentry",
    "Docker",
    "Postman",
    "Linear",
    "Tailscale",
    "Backblaze",
    "Twilio",
    "Stripe",
    "Let's Encrypt",
    # ── IT-Sicherheit / Datenschutz ──
    "Tenable / Nessus",
    "Greenbone / OpenVAS",
    "PortSwigger (Burp Suite)",
    "Veeam",
    "Have I Been Pwned",
    "TÜV / Zertifizierungsstelle",
    "DEKRA",
    "DataGuard",
    "Usercentrics",
    "Cookiebot",
    "eRecht24",
    # ── KI ──
    "Anthropic",
    "OpenAI",
    "Cursor",
    "Google (Gemini)",
    "Mistral AI",
    "Hugging Face",
    "ElevenLabs",
    # ── Telekommunikation ──
    "Telekom",
    "Vodafone",
    "o2 / Telefónica",
    "1&1",
    "sipgate",
    # ── Büro / Betrieb ──
    "Amazon",
    "Amazon Business",
    "Conrad",
    "Galaxus",
    "Reichelt",
    "IKEA",
    "OBI / Baumarkt",
    "Deutsche Post",
    "DHL",
    "Deutsche Bahn",
    "Tankstelle",
    "REWE / Supermarkt",
    # ── Versicherung / Beiträge ──
    "IHK",
    "Berufshaftpflicht",
    "Krankenversicherung",
    "Rentenversicherung",
]

_TAETIGKEIT = [
    # ── Entwicklung ──
    "Frontend-Entwicklung",
    "Backend-Entwicklung",
    "Fullstack-Entwicklung",
    "API-Entwicklung",
    "Datenbankentwicklung",
    "App-Entwicklung",
    "Schnittstellenentwicklung",
    "Plugin-Entwicklung",
    "Skript-Entwicklung / Automatisierung",
    "Code-Review",
    "Refactoring",
    "Bugfixing",
    "Testing / QA",
    "Deployment / Release",
    # ── Website ──
    "Website-Erstellung",
    "Website-Pflege",
    "Website-Redesign",
    "Landing Page",
    "SEO-Optimierung",
    "Performance-Optimierung",
    "Content-Pflege",
    # ── Infrastruktur / Security ──
    "Server-Administration",
    "Server-Einrichtung",
    "Hosting-Migration",
    "Backup-Einrichtung",
    "Monitoring-Einrichtung",
    "Security-Audit",
    "Security-Härtung",
    "Penetrationstest",
    "Schwachstellenanalyse",
    "Schwachstellen-Nachtest (Retest)",
    "Update / Patching",
    "Incident-Response",
    "Forensische Analyse",
    "Notfallübung",
    "Risikoanalyse",
    "Schutzbedarfsfeststellung",
    "ISMS-Aufbau (ISO 27001)",
    "ISMS-Betreuung",
    "Internes Audit (ISO 27001)",
    "Auditbegleitung / Zertifizierungsaudit",
    "Richtlinienerstellung",
    "Berechtigungskonzept",
    "IT-Grundschutz-Umsetzung",
    "NIS2-Beratung",
    "Awareness-Schulung",
    "Phishing-Simulation",
    "Security-Konzept",
    # ── Datenschutz / DSB ──
    "Externe DSB-Tätigkeit",
    "Verarbeitungsverzeichnis (VVT)",
    "TOM-Dokumentation",
    "AVV-Prüfung",
    "Datenschutz-Folgenabschätzung",
    "Betroffenenanfrage bearbeiten",
    "Datenpanne / Meldung Art. 33",
    "Löschkonzept",
    "Datenschutz-Audit",
    "Datenschutz-Schulung",
    "Website-Datenschutzprüfung",
    "KI-Compliance-Beratung (KI-VO)",
    # ── Softwareentwicklung — Detailtätigkeiten ──
    "Architektur / Systemdesign",
    "Datenmodellierung",
    "Prototyping",
    "UI-/UX-Design",
    "Barrierefreiheit (WCAG)",
    "Unit-Tests",
    "Integrationstests",
    "End-to-End-Tests",
    "Testautomatisierung",
    "CI/CD-Einrichtung",
    "Containerisierung (Docker)",
    "Infrastruktur als Code",
    "Datenmigration",
    "Legacy-Migration",
    "Technische Analyse / Machbarkeit",
    "Pair Programming",
    "Technisches Konzept",
    "Lastenheft / Pflichtenheft",
    "Abnahmebegleitung",
    "Fehleranalyse (Debugging)",
    "Bereitschaft / On-Call",
    # ── Beratung / Kommunikation ──
    "Beratung",
    "IT-Beratung",
    "Datenschutz-Beratung",
    "DSGVO-Dokumentation",
    "Anforderungsanalyse",
    "Konzeption",
    "Angebotserstellung",
    "Kundentermin",
    "Telefonat",
    "E-Mail-Kommunikation",
    "Projektmanagement",
    "Dokumentation",
    "Schulung / Einweisung",
    "Support",
    "Wartung",
    "Recherche",
]

_TODO = [
    # Akquise & Kontakt
    "Angebot nachfassen",
    "Rückruf vereinbaren",
    "Termin bestätigen",
    "Termin vorbereiten",
    "Gesprächsnotiz nachtragen",
    "Kontaktdaten prüfen",
    "Ansprechpartner ermitteln",
    "Unterlagen zusenden",
    "Referenzen schicken",
    "Preisliste schicken",
    # Angebot & Auftrag
    "Angebot erstellen",
    "Angebot überarbeiten",
    "Aufwand schätzen",
    "Leistungsumfang klären",
    "Auftragsbestätigung einholen",
    "Projektstart planen",
    "Zwischenstand abstimmen",
    "Abnahme vereinbaren",
    "Projekt abschließen",
    # Rechnung & Zahlung
    "Rechnung stellen",
    "Rechnung prüfen",
    "Zahlungseingang prüfen",
    "Zahlung anmahnen",
    "Stundennachweis erstellen",
    "Beleg ablegen",
    # Verträge & Recht
    "Vertrag prüfen",
    "Vertrag verlängern",
    "Kündigungsfrist prüfen",
    "AVV einholen",
    "AGB aktualisieren",
    "Datenschutz-Unterlagen prüfen",
    # Technik & Betrieb
    "Website-Analyse durchführen",
    "Backup prüfen",
    "Backup-Wiederherstellung testen",
    "Update einspielen",
    "Sicherheitsupdates einspielen",
    "Zugangsdaten übergeben",
    "Zugangsdaten rotieren",
    "Domain verlängern",
    "DNS-Eintrag anpassen",
    "SSL-Zertifikat prüfen",
    "SSL-Zertifikat erneuern",
    "Monitoring einrichten",
    "Monitoring-Alarm prüfen",
    "Fehler analysieren",
    "Logs auswerten",
    "Speicherplatz prüfen",
    "Serverkosten prüfen",
    "Hosting-Vertrag prüfen",
    # Softwareentwicklung
    "Anforderungen klären",
    "Aufwand schätzen (Story Points)",
    "Tickets anlegen",
    "Sprint planen",
    "Feature umsetzen",
    "Bug reproduzieren",
    "Bug beheben",
    "Hotfix ausrollen",
    "Code-Review durchführen",
    "Pull Request prüfen",
    "Merge-Konflikte auflösen",
    "Refactoring durchführen",
    "Technische Schuld abbauen",
    "Unit-Tests ergänzen",
    "Integrationstests schreiben",
    "E2E-Tests aktualisieren",
    "Testabdeckung prüfen",
    "CI-Pipeline reparieren",
    "Build-Fehler beheben",
    "Deployment durchführen",
    "Release vorbereiten",
    "Release Notes schreiben",
    "Rollback vorbereiten",
    "Datenbank-Migration einspielen",
    "Datenmodell anpassen",
    "API-Dokumentation aktualisieren",
    "Schnittstelle testen",
    "Abhängigkeiten aktualisieren",
    "Dependency-Schwachstellen prüfen",
    "Lizenzen der Abhängigkeiten prüfen",
    "Performance-Profiling durchführen",
    "Ladezeiten optimieren",
    "Datenbank-Query optimieren",
    "Caching einrichten",
    "Fehlermonitoring einrichten (Sentry)",
    "Feature-Flag entfernen",
    "Altsystem abschalten",
    "Datenmigration planen",
    "Staging-Umgebung aufsetzen",
    "Entwicklungsumgebung dokumentieren",
    "Repository aufräumen",
    "Secrets aus dem Code entfernen",
    "Barrierefreiheit prüfen",
    "Responsives Verhalten prüfen",
    "Browser-Kompatibilität testen",
    "Abnahmetest mit Kunde durchführen",
    "Übergabe an den Kunden vorbereiten",
    # IT-Sicherheit (ISO 27001 / IT-Grundschutz)
    "Schwachstellenscan durchführen",
    "Penetrationstest planen",
    "Penetrationstest-Bericht erstellen",
    "Sicherheitslücke bewerten (CVSS)",
    "Patch-Stand prüfen",
    "Härtung umsetzen",
    "Firewall-Regeln prüfen",
    "Zugriffsrechte überprüfen",
    "Berechtigungskonzept aktualisieren",
    "Admin-Konten inventarisieren",
    "MFA aktivieren",
    "Passwortrichtlinie prüfen",
    "Notfallplan aktualisieren",
    "Notfallübung planen",
    "Incident dokumentieren",
    "Sicherheitsvorfall nachbereiten",
    "Risikoanalyse durchführen",
    "Risikobehandlungsplan aktualisieren",
    "Asset-Inventar aktualisieren",
    "Schutzbedarfsfeststellung durchführen",
    "ISMS-Dokumentation pflegen",
    "Statement of Applicability aktualisieren",
    "Internes Audit vorbereiten",
    "Internes Audit durchführen",
    "Auditfeststellungen abarbeiten",
    "Managementbewertung vorbereiten",
    "Richtlinie überarbeiten",
    "Dienstleister sicherheitstechnisch bewerten",
    "Backup-Konzept prüfen",
    "Phishing-Simulation auswerten",
    "Awareness-Schulung planen",
    "Awareness-Schulung durchführen",
    "Schulungsnachweis dokumentieren",
    "NIS2-Betroffenheit prüfen",
    "Sicherheitskennzahlen auswerten",
    # Datenschutz (DSGVO / DSB-Mandat)
    "Verarbeitungsverzeichnis aktualisieren",
    "TOM dokumentieren",
    "AVV prüfen",
    "AVV abschließen",
    "Auftragsverarbeiter prüfen",
    "Datenschutzerklärung aktualisieren",
    "Cookie-Banner prüfen",
    "Einwilligungen prüfen",
    "Löschkonzept erstellen",
    "Löschfristen prüfen",
    "Betroffenenanfrage beantworten",
    "Auskunftsersuchen bearbeiten",
    "Datenpanne melden (Art. 33)",
    "Datenschutz-Folgenabschätzung durchführen",
    "Datenschutz-Schulung durchführen",
    "Verpflichtung auf Vertraulichkeit einholen",
    "Datenschutz-Audit vorbereiten",
    "Datenschutz-Jahresbericht erstellen",
    "Drittlandtransfer prüfen",
    "Rechtsgrundlage dokumentieren",
    "KI-Einsatz datenschutzrechtlich bewerten",
    "KI-Verordnung: Betroffenheit prüfen",
    "Meldung an die Aufsichtsbehörde vorbereiten",
    "DSB-Bestellung dokumentieren",
    # Organisation
    "Rückmeldung geben",
    "Wiedervorlage",
    "Recherche durchführen",
    "Dokumentation aktualisieren",
    "Nachbereitung",
    "Fortbildung einplanen",
    "Zertifizierung auffrischen",
    "Fachliteratur sichten",
    "Zeiterfassung nachtragen",
    "Reisekosten abrechnen",
]

_TARGET = [
    # Software / Entwicklung
    "Individualsoftware-Bedarf",
    "Legacy-Modernisierung",
    "Projektron BCS / Zeiterfassung",
    "Zeiterfassungs-Pflicht (BAG-Urteil)",
    "Projektmanagement-Software",
    "Schnittstellen / Systemintegration",
    "Ablösung Excel-Insellösung",
    "Prozessautomatisierung / KI",
    "Website veraltet / Relaunch",
    "Online-Shop / E-Commerce",
    "Barrierefreiheit (BFSG-Pflicht)",
    "PageSpeed / SEO schwach",
    # IT-Sicherheit
    "IT-Sicherheit / ISO 27001",
    "IT-Grundschutz (BSI)",
    "NIS2-Betroffenheit",
    "Ransomware-Vorsorge",
    "Security-Awareness / Phishing",
    "Kein Notfallplan (BCM)",
    "Veraltete Infrastruktur / Patch-Rückstand",
    "Cyber-Versicherung: Auflagen",
    # Datenschutz
    "Datenschutz / externer DSB",
    "DSGVO-Abmahnrisiko Website",
    "Fehlende Verarbeitungsübersicht (VVT)",
    "Auftragsverarbeitung ungeregelt (AVV)",
    "Datenpanne / Meldepflicht",
    "KI-Verordnung (KI-VO) Betroffenheit",
    # Vertrieb / Beziehung
    "Bestandskunde: Cross-Selling",
    "Bestandskunde: Wartungsvertrag",
    "Empfehlung / Warmkontakt",
    "Ausschreibung / RFP",
    "Wettbewerber-Wechsel",
]

TAXONOMIES: dict[str, list[str]] = {
    "role": list(dict.fromkeys(_ROLE)),
    "todo": list(dict.fromkeys(_TODO)),
    "target": list(dict.fromkeys(_TARGET)),
    "source": list(dict.fromkeys(_SOURCE)),
    "tag": _TAG,
    "branche": list(dict.fromkeys(_BRANCHE)),
    "zielsystem": list(dict.fromkeys(_ZIELSYSTEM)),
    "vendor": list(dict.fromkeys(_VENDOR)),
    "taetigkeit": list(dict.fromkeys(_TAETIGKEIT)),
}

# Synonym → kanonische Schreibweise (Keys werden gefoldet verglichen).
SYNONYMS: dict[str, str] = {
    # Rollen
    "gf": "Geschäftsführung",
    "geschaftsfuhrer": "Geschäftsführung",
    "geschaftsfuhrerin": "Geschäftsführung",
    "geschaftsfuhrung": "Geschäftsführung",
    "ceo": "Geschäftsführung",
    "managing director": "Geschäftsführung",
    "owner": "Inhaber/in",
    "inhaber": "Inhaber/in",
    "inhaberin": "Inhaber/in",
    "dsb": "Datenschutzbeauftragte/r",
    "datenschutzbeauftragter": "Datenschutzbeauftragte/r",
    "it leiter": "IT-Leitung",
    "it-leiter": "IT-Leitung",
    "head of it": "IT-Leitung",
    # Quellen
    "linked in": "LinkedIn",
    "osm": "OpenStreetMap",
    "ki recherche": "KI-Recherche",
    "kaltakquise": "Kaltakquise Telefon",
    "empfehlungen": "Empfehlung",
    # Tags / Branchen
    "dsvgo": "DSGVO",
    "dsgvo": "DSGVO",
    "hausverwaltungen": "Hausverwaltung",
    "steuerberaterin": "Steuerberater",
    "steuerkanzlei": "Steuerberater",
    "makler": "Immobilienmakler",
    "onlineshop": "E-Commerce / Onlineshop",
    "e-commerce": "E-Commerce / Onlineshop",
    "webshop": "Webshop",
    "agentur": "Agentur / IT-Dienstleister",
    # Zielsysteme
    "datev online": "DATEV Unternehmen online",
    "business central": "Microsoft Dynamics NAV / Business Central",
    "dynamics": "Microsoft Dynamics 365",
    "office 365": "Microsoft 365",
    "o365": "Microsoft 365",
    "m365": "Microsoft 365",
    # Vendors
    "1blu": "IONOS",
    "google": "Google Workspace",
    "msft": "Microsoft 365",
    "telefonica": "o2 / Telefónica",
}


# --------------------------------------------------------------------------- #
#  Normalisierung (rein)
# --------------------------------------------------------------------------- #
def fold(s: str) -> str:
    """Vergleichs-Schlüssel: trim, lowercase, Diakritika weg (ä→a, é→e)."""
    nfkd = unicodedata.normalize("NFKD", (s or "").strip().lower())
    return "".join(c for c in nfkd if not unicodedata.combining(c))


_SYNONYMS_FOLDED = {fold(k): v for k, v in SYNONYMS.items()}
_CANONICAL_BY_FOLD: dict[str, dict[str, str]] = {
    field: {fold(v): v for v in values} for field, values in TAXONOMIES.items()
}


def canonicalize(field: str, value: str) -> str:
    """Kanonische Schreibweise: Synonym-Treffer → kanonisch; sonst Case-Variante
    eines kuratierten Werts → kuratierte Schreibweise; sonst Original (getrimmt).
    Creatable: unbekannte Werte bleiben unangetastet erlaubt."""
    v = (value or "").strip()
    if not v:
        return v
    key = fold(v)
    if key in _SYNONYMS_FOLDED:
        return _SYNONYMS_FOLDED[key]
    return _CANONICAL_BY_FOLD.get(field, {}).get(key, v)


def merge_suggestions(field: str, own_counts: dict[str, int],
                      q: str = "", limit: int = 50) -> list[str]:
    """Kuratierte Liste ∪ eigene Bestandswerte, fold-dedupliziert (kuratierte
    Schreibweise gewinnt). Ranking: eigene Häufigkeit desc → alphabetisch.
    Optionaler Substring-Filter q (gefoldet)."""
    counts_folded: dict[str, int] = {}
    for raw, n in own_counts.items():
        canon = canonicalize(field, raw)
        counts_folded[fold(canon)] = counts_folded.get(fold(canon), 0) + n

    merged: dict[str, str] = {}          # fold-key → Anzeige-Schreibweise
    for v in TAXONOMIES.get(field, []):
        merged.setdefault(fold(v), v)
    for raw in own_counts:
        canon = canonicalize(field, raw)
        merged.setdefault(fold(canon), canon)

    items = list(merged.items())
    if q:
        qf = fold(q)
        items = [(k, v) for k, v in items if qf in k]
    items.sort(key=lambda kv: (-counts_folded.get(kv[0], 0), kv[1].lower()))
    return [v for _, v in items[:limit]]
